const fighters = [
    // =========================================================================
    // HEAVYWEIGHT (ТЯЖЕЛЫЙ ВЕС - до 120 кг)
    // =========================================================================
    {
        id: "tom_aspinall",
        name: "Tom Aspinall",
        nickname: "—",
        division: "Heavyweight",
        rank: "C",
        record: "15-3-0",
        sherdog: { ko: 11, sub: 3, dec: 1, lossesKo: 1, lossesSub: 1, lossesDec: 1 },
        ufcStats: { slpm: 7.72, strAcc: 66, sapm: 2.77, strDef: 65, tdAvg: 2.30, tdAcc: 100, tdDef: 100 },
        verdictRating: 985,
        nationality: "UK",
        flag: "🇬🇧",
        height: "6'5\" (196 cm)",
        reach: "78.0\" (198 cm)",
        stance: "Orthodox",
        age: 33,
        stats: { striking: 95, wrestling: 91, grappling: 93, cardio: 92, power: 98, defense: 90 },
        bio: "UFC Heavyweight Champion. Known for unprecedented speed for a heavyweight, explosive combination boxing, and black-belt BJJ submissions.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4405527.png&w=350&h=254"
    },
    {
        id: "jon_jones",
        name: "Jon Jones",
        nickname: "Bones",
        division: "Heavyweight",
        rank: 1,
        record: "27-1-0 (1 NC)",
        sherdog: { ko: 10, sub: 7, dec: 10, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.30, strAcc: 57, sapm: 2.22, strDef: 64, tdAvg: 1.85, tdAcc: 45, tdDef: 95 },
        verdictRating: 995,
        nationality: "USA",
        flag: "🇺🇸",
        height: "6'4\" (193 cm)",
        reach: "84.5\" (215 cm)",
        stance: "Orthodox",
        age: 38,
        stats: { striking: 88, wrestling: 97, grappling: 93, cardio: 91, power: 86, defense: 96 },
        bio: "Widely regarded as the greatest MMA fighter of all time. Former long-time Light Heavyweight Champion and Heavyweight Champion.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335639.png&w=350&h=254"
    },
    {
        id: "ciryl_gane",
        name: "Ciryl Gane",
        nickname: "Bon Gamin",
        division: "Heavyweight",
        rank: 2,
        record: "12-2-0",
        sherdog: { ko: 6, sub: 3, dec: 3, lossesKo: 0, lossesSub: 1, lossesDec: 1 },
        ufcStats: { slpm: 5.06, strAcc: 59, sapm: 2.25, strDef: 62, tdAvg: 0.61, tdAcc: 22, tdDef: 42 },
        verdictRating: 910,
        nationality: "France",
        flag: "🇫🇷",
        height: "6'4\" (193 cm)",
        reach: "81.0\" (206 cm)",
        stance: "Orthodox",
        age: 35,
        stats: { striking: 94, wrestling: 65, grappling: 68, cardio: 93, power: 85, defense: 88 },
        bio: "Former Interim Heavyweight Champion. A remarkably agile footwork kickboxer with muay thai roots.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4567220.png&w=350&h=254"
    },
    {
        id: "alexander_volkov",
        name: "Alexander Volkov",
        nickname: "Drago",
        division: "Heavyweight",
        rank: 3,
        record: "38-10-0",
        sherdog: { ko: 24, sub: 4, dec: 10, lossesKo: 2, lossesSub: 3, lossesDec: 5 },
        ufcStats: { slpm: 4.90, strAcc: 57, sapm: 3.00, strDef: 53, tdAvg: 0.52, tdAcc: 70, tdDef: 73 },
        verdictRating: 900,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "6'7\" (201 cm)",
        reach: "80.0\" (203 cm)",
        stance: "Orthodox",
        age: 37,
        stats: { striking: 91, wrestling: 78, grappling: 80, cardio: 92, power: 87, defense: 88 },
        bio: "Towering heavyweight contender. Technical volume kickboxer with vast experience across international promotions.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3025883.png&w=350&h=254"
    },
    {
        id: "sergei_pavlovich",
        name: "Sergei Pavlovich",
        nickname: "—",
        division: "Heavyweight",
        rank: 4,
        record: "18-3-0",
        sherdog: { ko: 15, sub: 0, dec: 3, lossesKo: 2, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 6.30, strAcc: 48, sapm: 4.60, strDef: 54, tdAvg: 0.00, tdAcc: 0, tdDef: 75 },
        verdictRating: 890,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "6'3\" (191 cm)",
        reach: "84.0\" (213 cm)",
        stance: "Southpaw",
        age: 34,
        stats: { striking: 93, wrestling: 75, grappling: 72, cardio: 80, power: 99, defense: 81 },
        bio: "Ferocious knock-out artist holding a historic streak of first-round KO finishes in the UFC.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4397079.png&w=350&h=254"
    },
    {
        id: "curtis_blaydes",
        name: "Curtis Blaydes",
        nickname: "Razor",
        division: "Heavyweight",
        rank: 5,
        record: "18-5-0 (1 NC)",
        sherdog: { ko: 13, sub: 0, dec: 5, lossesKo: 5, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 3.56, strAcc: 49, sapm: 1.87, strDef: 60, tdAvg: 5.72, tdAcc: 53, tdDef: 33 },
        verdictRating: 875,
        nationality: "USA",
        flag: "🇺🇸",
        height: "6'3\" (191 cm)",
        reach: "80.0\" (203 cm)",
        stance: "Orthodox",
        age: 35,
        stats: { striking: 78, wrestling: 96, grappling: 85, cardio: 88, power: 88, defense: 83 },
        bio: "NCAA Division I wrestler holding the record for most takedowns in UFC heavyweight history.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3902120.png&w=350&h=254"
    },
    {
        id: "jailton_almeida",
        name: "Jailton Almeida",
        nickname: "Malhadinho",
        division: "Heavyweight",
        rank: 6,
        record: "21-3-0",
        sherdog: { ko: 7, sub: 13, dec: 1, lossesKo: 2, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 2.54, strAcc: 64, sapm: 0.77, strDef: 45, tdAvg: 5.10, tdAcc: 58, tdDef: 50 },
        verdictRating: 885,
        nationality: "Brazil",
        flag: "🇧🇷",
        height: "6'3\" (191 cm)",
        reach: "79.0\" (200 cm)",
        stance: "Orthodox",
        age: 34,
        stats: { striking: 72, wrestling: 95, grappling: 97, cardio: 90, power: 82, defense: 87 },
        bio: "Brazilian grappling specialist with relentless double-leg takedowns and top-mount control.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4898144.png&w=350&h=254"
    },

    // =========================================================================
    // LIGHT HEAVYWEIGHT (ПОЛУТЯЖЕЛЫЙ ВЕС - до 93 кг)
    // =========================================================================
    {
        id: "alex_pereira",
        name: "Alex Pereira",
        nickname: "Poatan",
        division: "Light Heavyweight",
        rank: "C",
        record: "12-2-0",
        sherdog: { ko: 10, sub: 0, dec: 2, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 5.23, strAcc: 63, sapm: 3.51, strDef: 51, tdAvg: 0.18, tdAcc: 100, tdDef: 70 },
        verdictRating: 980,
        nationality: "Brazil",
        flag: "🇧🇷",
        height: "6'4\" (193 cm)",
        reach: "79.0\" (200 cm)",
        stance: "Orthodox",
        age: 38,
        stats: { striking: 99, wrestling: 68, grappling: 70, cardio: 88, power: 100, defense: 85 },
        bio: "UFC Light Heavyweight Champion & former Middleweight Champion. Legendary Glory Kickboxing two-division champion with a world-famous left hook.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4873429.png&w=350&h=254"
    },
    {
        id: "magomed_ankalaev",
        name: "Magomed Ankalaev",
        nickname: "—",
        division: "Light Heavyweight",
        rank: 1,
        record: "19-1-1 (1 NC)",
        sherdog: { ko: 10, sub: 0, dec: 9, lossesKo: 0, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 3.64, strAcc: 52, sapm: 2.25, strDef: 64, tdAvg: 1.02, tdAcc: 31, tdDef: 86 },
        verdictRating: 945,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "6'3\" (191 cm)",
        reach: "75.0\" (191 cm)",
        stance: "Orthodox",
        age: 34,
        stats: { striking: 92, wrestling: 94, grappling: 90, cardio: 93, power: 88, defense: 94 },
        bio: "Master of Sport in Combat Sambo and Greco-Roman wrestling. Methodical counter-striker with iron defense.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4307521.png&w=350&h=254"
    },
    {
        id: "jiri_prochazka",
        name: "Jiří Procházka",
        nickname: "Denisa",
        division: "Light Heavyweight",
        rank: 2,
        record: "30-5-1",
        sherdog: { ko: 26, sub: 3, dec: 1, lossesKo: 4, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 5.75, strAcc: 55, sapm: 5.43, strDef: 40, tdAvg: 0.68, tdAcc: 100, tdDef: 68 },
        verdictRating: 930,
        nationality: "Czech Republic",
        flag: "🇨🇿",
        height: "6'3\" (191 cm)",
        reach: "80.0\" (203 cm)",
        stance: "Switch",
        age: 33,
        stats: { striking: 95, wrestling: 75, grappling: 82, cardio: 92, power: 95, defense: 76 },
        bio: "Former Light Heavyweight Champion. Wild, unpredictable Bushido samurai fighting style.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4704381.png&w=350&h=254"
    },
    {
        id: "jan_blachowicz",
        name: "Jan Błachowicz",
        nickname: "Legendary Polish Power",
        division: "Light Heavyweight",
        rank: 4,
        record: "29-10-1",
        sherdog: { ko: 9, sub: 9, dec: 11, lossesKo: 2, lossesSub: 1, lossesDec: 7 },
        ufcStats: { slpm: 3.41, strAcc: 49, sapm: 2.87, strDef: 54, tdAvg: 0.97, tdAcc: 53, tdDef: 68 },
        verdictRating: 890,
        nationality: "Poland",
        flag: "🇵🇱",
        height: "6'2\" (188 cm)",
        reach: "78.0\" (198 cm)",
        stance: "Orthodox",
        age: 43,
        stats: { striking: 88, wrestling: 84, grappling: 87, cardio: 86, power: 92, defense: 88 },
        bio: "Former Light Heavyweight Champion famous for his body kicks and heavy Polish hands.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3153110.png&w=350&h=254"
    },
    {
        id: "jamahal_hill",
        name: "Jamahal Hill",
        nickname: "Sweet Dreams",
        division: "Light Heavyweight",
        record: "12-2-0 (1 NC)",
        sherdog: { ko: 7, sub: 0, dec: 5, lossesKo: 2, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 6.90, strAcc: 54, sapm: 3.60, strDef: 52, tdAvg: 0.00, tdAcc: 0, tdDef: 73 },
        verdictRating: 885,
        nationality: "USA",
        flag: "🇺🇸",
        height: "6'4\" (193 cm)",
        reach: "79.0\" (200 cm)",
        stance: "Southpaw",
        age: 35,
        stats: { striking: 93, wrestling: 70, grappling: 68, cardio: 87, power: 92, defense: 82 },
        bio: "Former Light Heavyweight Champion with crisp, high-volume southpaw boxing.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4397148.png&w=350&h=254"
    },

    // =========================================================================
    // MIDDLEWEIGHT (СРЕДНИЙ ВЕС - до 84 кг)
    // =========================================================================
    {
        id: "dricus_du_plessis",
        name: "Dricus du Plessis",
        nickname: "Stillknocks",
        division: "Middleweight",
        rank: "C",
        record: "22-2-0",
        sherdog: { ko: 9, sub: 10, dec: 3, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 6.49, strAcc: 50, sapm: 3.79, strDef: 53, tdAvg: 3.00, tdAcc: 50, tdDef: 50 },
        verdictRating: 960,
        nationality: "South Africa",
        flag: "🇿🇦",
        height: "6'1\" (185 cm)",
        reach: "76.0\" (193 cm)",
        stance: "Switch",
        age: 32,
        stats: { striking: 89, wrestling: 91, grappling: 88, cardio: 95, power: 94, defense: 85 },
        bio: "UFC Middleweight Champion. Unorthodox pressure fighter with explosive power and relentless grappling.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4685361.png&w=350&h=254"
    },
    {
        id: "sean_strickland",
        name: "Sean Strickland",
        nickname: "Tarzan",
        division: "Middleweight",
        rank: 1,
        record: "29-6-0",
        sherdog: { ko: 11, sub: 4, dec: 14, lossesKo: 2, lossesSub: 0, lossesDec: 4 },
        ufcStats: { slpm: 5.89, strAcc: 41, sapm: 4.20, strDef: 65, tdAvg: 0.85, tdAcc: 64, tdDef: 84 },
        verdictRating: 935,
        nationality: "USA",
        flag: "🇺🇸",
        height: "6'1\" (185 cm)",
        reach: "76.0\" (193 cm)",
        stance: "Orthodox",
        age: 35,
        stats: { striking: 93, wrestling: 84, grappling: 80, cardio: 97, power: 82, defense: 96 },
        bio: "Former Middleweight Champion. Defensive boxing specialist utilizing the Philly Shell stance.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3044158.png&w=350&h=254"
    },
    {
        id: "israel_adesanya",
        name: "Israel Adesanya",
        nickname: "The Last Stylebender",
        division: "Middleweight",
        rank: 2,
        record: "24-4-0",
        sherdog: { ko: 16, sub: 0, dec: 8, lossesKo: 1, lossesSub: 1, lossesDec: 2 },
        ufcStats: { slpm: 3.93, strAcc: 48, sapm: 3.11, strDef: 56, tdAvg: 0.06, tdAcc: 14, tdDef: 77 },
        verdictRating: 940,
        nationality: "New Zealand",
        flag: "🇳🇿",
        height: "6'4\" (193 cm)",
        reach: "80.0\" (203 cm)",
        stance: "Switch",
        age: 37,
        stats: { striking: 98, wrestling: 72, grappling: 70, cardio: 93, power: 88, defense: 92 },
        bio: "Two-time UFC Middleweight Champion. World-class kickboxer renowned for technical counter-striking.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4285663.png&w=350&h=254"
    },
    {
        id: "robert_whittaker",
        name: "Robert Whittaker",
        nickname: "The Reaper",
        division: "Middleweight",
        rank: 3,
        record: "26-8-0",
        sherdog: { ko: 10, sub: 5, dec: 11, lossesKo: 3, lossesSub: 2, lossesDec: 3 },
        ufcStats: { slpm: 4.47, strAcc: 42, sapm: 3.37, strDef: 60, tdAvg: 0.80, tdAcc: 37, tdDef: 82 },
        verdictRating: 920,
        nationality: "Australia",
        flag: "🇦🇺",
        height: "6'0\" (183 cm)",
        reach: "73.5\" (187 cm)",
        stance: "Orthodox",
        age: 35,
        stats: { striking: 94, wrestling: 90, grappling: 84, cardio: 92, power: 87, defense: 91 },
        bio: "Former Middleweight Champion. Blitz karate technician with legendary anti-wrestling defense.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2967674.png&w=350&h=254"
    },
    {
        id: "khamzat_chimaev",
        name: "Khamzat Chimaev",
        nickname: "Borz",
        division: "Middleweight",
        rank: 4,
        record: "14-0-0",
        sherdog: { ko: 6, sub: 6, dec: 2, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 5.72, strAcc: 58, sapm: 3.46, strDef: 42, tdAvg: 3.99, tdAcc: 46, tdDef: 100 },
        verdictRating: 965,
        nationality: "UAE / Russia",
        flag: "🇦🇪",
        height: "6'2\" (188 cm)",
        reach: "75.0\" (190 cm)",
        stance: "Orthodox",
        age: 32,
        stats: { striking: 82, wrestling: 99, grappling: 95, cardio: 84, power: 94, defense: 88 },
        bio: "Undefeated phenom known for extreme aggression, ragdoll wrestling, and fast submission finishes.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4687640.png&w=350&h=254"
    },

    // =========================================================================
    // WELTERWEIGHT (ПОЛУСРЕДНИЙ ВЕС - до 77 кг)
    // =========================================================================
    {
        id: "belal_muhammad",
        name: "Belal Muhammad",
        nickname: "Remember the Name",
        division: "Welterweight",
        rank: "C",
        record: "24-3-0 (1 NC)",
        sherdog: { ko: 5, sub: 1, dec: 18, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 4.29, strAcc: 43, sapm: 3.64, strDef: 57, tdAvg: 2.47, tdAcc: 35, tdDef: 92 },
        verdictRating: 940,
        nationality: "USA / Palestine",
        flag: "🇵🇸",
        height: "5'11\" (180 cm)",
        reach: "72.0\" (183 cm)",
        stance: "Orthodox",
        age: 38,
        stats: { striking: 87, wrestling: 96, grappling: 90, cardio: 99, power: 80, defense: 94 },
        bio: "UFC Welterweight Champion. High-tempo pressure wrestler with boundless conditioning.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3947477.png&w=350&h=254"
    },
    {
        id: "shavkat_rakhmonov",
        name: "Shavkat Rakhmonov",
        nickname: "Nomad",
        division: "Welterweight",
        rank: 1,
        record: "18-0-0",
        sherdog: { ko: 8, sub: 10, dec: 0, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.38, strAcc: 56, sapm: 2.61, strDef: 54, tdAvg: 1.49, tdAcc: 57, tdDef: 100 },
        verdictRating: 975,
        nationality: "Kazakhstan",
        flag: "🇰🇿",
        height: "6'1\" (185 cm)",
        reach: "77.0\" (196 cm)",
        stance: "Orthodox",
        age: 31,
        stats: { striking: 93, wrestling: 95, grappling: 97, cardio: 92, power: 91, defense: 89 },
        bio: "Undefeated 100% finish rate fighter from Kazakhstan. Master of Sports Sambo & Muay Thai knees.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4685934.png&w=350&h=254"
    },
    {
        id: "leon_edwards",
        name: "Leon Edwards",
        nickname: "Rocky",
        division: "Welterweight",
        rank: 2,
        record: "22-4-0 (1 NC)",
        sherdog: { ko: 7, sub: 3, dec: 12, lossesKo: 0, lossesSub: 0, lossesDec: 4 },
        ufcStats: { slpm: 2.75, strAcc: 53, sapm: 2.40, strDef: 54, tdAvg: 1.25, tdAcc: 34, tdDef: 68 },
        verdictRating: 920,
        nationality: "UK",
        flag: "🇬🇧",
        height: "6'2\" (188 cm)",
        reach: "74.0\" (188 cm)",
        stance: "Southpaw",
        age: 34,
        stats: { striking: 93, wrestling: 82, grappling: 83, cardio: 90, power: 82, defense: 92 },
        bio: "Former Welterweight Champion. Smooth technical southpaw striker with a historic head-kick KO victory.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3138804.png&w=350&h=254"
    },
    {
        id: "kamaru_usman",
        name: "Kamaru Usman",
        nickname: "The Nigerian Nightmare",
        division: "Welterweight",
        rank: 3,
        record: "20-4-0",
        sherdog: { ko: 9, sub: 1, dec: 10, lossesKo: 1, lossesSub: 1, lossesDec: 2 },
        ufcStats: { slpm: 4.57, strAcc: 52, sapm: 2.75, strDef: 56, tdAvg: 2.82, tdAcc: 48, tdDef: 97 },
        verdictRating: 930,
        nationality: "Nigeria / USA",
        flag: "🇳🇬",
        height: "6'0\" (183 cm)",
        reach: "76.0\" (193 cm)",
        stance: "Orthodox",
        age: 39,
        stats: { striking: 88, wrestling: 97, grappling: 91, cardio: 94, power: 89, defense: 93 },
        bio: "Former long-reigning Welterweight Champion with elite NCAA Division II wrestling roots.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3163446.png&w=350&h=254"
    },
    {
        id: "jack_della_maddalena",
        name: "Jack Della Maddalena",
        nickname: "—",
        division: "Welterweight",
        rank: 4,
        record: "17-2-0",
        sherdog: { ko: 12, sub: 2, dec: 3, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 7.20, strAcc: 53, sapm: 4.80, strDef: 67, tdAvg: 0.20, tdAcc: 20, tdDef: 82 },
        verdictRating: 915,
        nationality: "Australia",
        flag: "🇦🇺",
        height: "5'11\" (180 cm)",
        reach: "73.0\" (185 cm)",
        stance: "Switch",
        age: 29,
        stats: { striking: 95, wrestling: 75, grappling: 80, cardio: 91, power: 90, defense: 87 },
        bio: "Australian boxing prodigy with body-head combination punching and clutch submission defense.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4896792.png&w=350&h=254"
    },

    // =========================================================================
    // LIGHTWEIGHT (ЛЕГКИЙ ВЕС - до 70 кг)
    // =========================================================================
    {
        id: "islam_makhachev",
        name: "Islam Makhachev",
        nickname: "—",
        division: "Lightweight",
        rank: "C",
        record: "26-1-0",
        sherdog: { ko: 5, sub: 12, dec: 9, lossesKo: 1, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 3.17, strAcc: 60, sapm: 1.24, strDef: 61, tdAvg: 3.17, tdAcc: 60, tdDef: 90 },
        verdictRating: 990,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "5'10\" (178 cm)",
        reach: "70.5\" (179 cm)",
        stance: "Southpaw",
        age: 34,
        stats: { striking: 86, wrestling: 98, grappling: 97, cardio: 95, power: 82, defense: 94 },
        bio: "UFC Lightweight Champion & Pound-for-Pound #1. World Combat Sambo champion tutored by Khabib Nurmagomedov.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3153835.png&w=350&h=254"
    },
    {
        id: "arman_tsarukyan",
        name: "Arman Tsarukyan",
        nickname: "Ahalkalakets",
        division: "Lightweight",
        rank: 1,
        record: "22-3-0",
        sherdog: { ko: 9, sub: 5, dec: 8, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 3.88, strAcc: 48, sapm: 2.68, strDef: 54, tdAvg: 3.40, tdAcc: 36, tdDef: 75 },
        verdictRating: 955,
        nationality: "Armenia / Russia",
        flag: "🇦🇲",
        height: "5'7\" (170 cm)",
        reach: "72.0\" (183 cm)",
        stance: "Orthodox",
        age: 29,
        stats: { striking: 90, wrestling: 96, grappling: 92, cardio: 94, power: 88, defense: 90 },
        bio: "#1 Lightweight contender. Explosive wrestler with heavy head kicks and relentless ground control.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4416399.png&w=350&h=254"
    },
    {
        id: "charles_oliveira",
        name: "Charles Oliveira",
        nickname: "Do Bronx",
        division: "Lightweight",
        rank: 2,
        record: "34-10-0 (1 NC)",
        sherdog: { ko: 10, sub: 21, dec: 3, lossesKo: 4, lossesSub: 4, lossesDec: 2 },
        ufcStats: { slpm: 3.54, strAcc: 54, sapm: 3.19, strDef: 51, tdAvg: 2.30, tdAcc: 40, tdDef: 55 },
        verdictRating: 945,
        nationality: "Brazil",
        flag: "🇧🇷",
        height: "5'10\" (178 cm)",
        reach: "74.0\" (188 cm)",
        stance: "Orthodox",
        age: 36,
        stats: { striking: 93, wrestling: 80, grappling: 100, cardio: 88, power: 90, defense: 80 },
        bio: "Former Lightweight Champion holding the UFC all-time record for most submission victories (21).",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2504179.png&w=350&h=254"
    },
    {
        id: "justin_gaethje",
        name: "Justin Gaethje",
        nickname: "The Highlight",
        division: "Lightweight",
        rank: 3,
        record: "25-5-0",
        sherdog: { ko: 20, sub: 1, dec: 4, lossesKo: 3, lossesSub: 2, lossesDec: 0 },
        ufcStats: { slpm: 7.35, strAcc: 60, sapm: 7.50, strDef: 53, tdAvg: 0.13, tdAcc: 25, tdDef: 75 },
        verdictRating: 935,
        nationality: "USA",
        flag: "🇺🇸",
        height: "5'11\" (180 cm)",
        reach: "70.0\" (178 cm)",
        stance: "Orthodox",
        age: 37,
        stats: { striking: 95, wrestling: 85, grappling: 68, cardio: 90, power: 96, defense: 83 },
        bio: "Former BMF & Interim Lightweight Champion. Destructive leg chopper with unmatched fan-favorite violence.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3024043.png&w=350&h=254"
    },
    {
        id: "dustin_poirier",
        name: "Dustin Poirier",
        nickname: "The Diamond",
        division: "Lightweight",
        rank: 4,
        record: "30-9-0 (1 NC)",
        sherdog: { ko: 15, sub: 8, dec: 7, lossesKo: 3, lossesSub: 3, lossesDec: 3 },
        ufcStats: { slpm: 5.45, strAcc: 50, sapm: 4.29, strDef: 54, tdAvg: 1.34, tdAcc: 36, tdDef: 63 },
        verdictRating: 930,
        nationality: "USA",
        flag: "🇺🇸",
        height: "5'9\" (175 cm)",
        reach: "72.0\" (183 cm)",
        stance: "Southpaw",
        age: 37,
        stats: { striking: 96, wrestling: 78, grappling: 82, cardio: 93, power: 90, defense: 87 },
        bio: "Former Interim Lightweight Champion with elite southpaw boxing combination shifts.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2563742.png&w=350&h=254"
    },

    // =========================================================================
    // FEATHERWEIGHT (ПОЛУЛЕГКИЙ ВЕС - до 65 кг)
    // =========================================================================
    {
        id: "ilia_topuria",
        name: "Ilia Topuria",
        nickname: "El Matador",
        division: "Featherweight",
        rank: "C",
        record: "16-0-0",
        sherdog: { ko: 6, sub: 8, dec: 2, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.40, strAcc: 46, sapm: 3.35, strDef: 65, tdAvg: 1.92, tdAcc: 56, tdDef: 92 },
        verdictRating: 985,
        nationality: "Spain / Georgia",
        flag: "🇪🇸",
        height: "5'7\" (170 cm)",
        reach: "69.0\" (175 cm)",
        stance: "Orthodox",
        age: 29,
        stats: { striking: 96, wrestling: 89, grappling: 91, cardio: 91, power: 94, defense: 91 },
        bio: "Undefeated UFC Featherweight Champion. Devastating boxing combined with Greco-Roman grappling.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4688404.png&w=350&h=254"
    },
    {
        id: "alexander_volkanovski",
        name: "Alexander Volkanovski",
        nickname: "The Great",
        division: "Featherweight",
        rank: 1,
        record: "26-4-0",
        sherdog: { ko: 13, sub: 3, dec: 10, lossesKo: 3, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 6.19, strAcc: 50, sapm: 3.40, strDef: 58, tdAvg: 1.84, tdAcc: 37, tdDef: 70 },
        verdictRating: 950,
        nationality: "Australia",
        flag: "🇦🇺",
        height: "5'6\" (168 cm)",
        reach: "71.0\" (180 cm)",
        stance: "Orthodox",
        age: 37,
        stats: { striking: 95, wrestling: 90, grappling: 85, cardio: 98, power: 84, defense: 93 },
        bio: "Former long-reigning Featherweight Champion with masterful feints and relentless volume.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3932742.png&w=350&h=254"
    },
    {
        id: "max_holloway",
        name: "Max Holloway",
        nickname: "Blessed",
        division: "Featherweight",
        rank: 2,
        record: "26-8-0",
        sherdog: { ko: 12, sub: 2, dec: 12, lossesKo: 1, lossesSub: 1, lossesDec: 6 },
        ufcStats: { slpm: 7.17, strAcc: 47, sapm: 4.72, strDef: 59, tdAvg: 0.27, tdAcc: 53, tdDef: 84 },
        verdictRating: 960,
        nationality: "USA",
        flag: "🇺🇸",
        height: "5'11\" (180 cm)",
        reach: "69.0\" (175 cm)",
        stance: "Orthodox",
        age: 34,
        stats: { striking: 97, wrestling: 72, grappling: 74, cardio: 100, power: 82, defense: 91 },
        bio: "BMF & former Featherweight Champion holding the UFC all-time record for most strikes landed.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2614902.png&w=350&h=254"
    },
    {
        id: "movsar_evloev",
        name: "Movsar Evloev",
        nickname: "—",
        division: "Featherweight",
        rank: 4,
        record: "18-0-0",
        sherdog: { ko: 3, sub: 4, dec: 11, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.30, strAcc: 49, sapm: 2.70, strDef: 63, tdAvg: 4.71, tdAcc: 51, tdDef: 71 },
        verdictRating: 930,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "5'7\" (170 cm)",
        reach: "72.0\" (183 cm)",
        stance: "Orthodox",
        age: 32,
        stats: { striking: 82, wrestling: 98, grappling: 93, cardio: 97, power: 74, defense: 95 },
        bio: "Undefeated Greco-Roman wrestling prodigy with high-altitude endurance and control.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4417088.png&w=350&h=254"
    },
    {
        id: "diego_lopes",
        name: "Diego Lopes",
        nickname: "—",
        division: "Featherweight",
        rank: 3,
        record: "26-6-0",
        sherdog: { ko: 10, sub: 12, dec: 4, lossesKo: 2, lossesSub: 0, lossesDec: 4 },
        ufcStats: { slpm: 3.22, strAcc: 52, sapm: 4.10, strDef: 41, tdAvg: 0.80, tdAcc: 33, tdDef: 46 },
        verdictRating: 915,
        nationality: "Brazil",
        flag: "🇧🇷",
        height: "5'11\" (180 cm)",
        reach: "72.5\" (184 cm)",
        stance: "Orthodox",
        age: 31,
        stats: { striking: 91, wrestling: 80, grappling: 96, cardio: 89, power: 90, defense: 84 },
        bio: "Aggressive crowd-pleaser combining dangerous wild punch power with elite BJJ submissions.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4898230.png&w=350&h=254"
    },

    // =========================================================================
    // BANTAMWEIGHT (ЛЕГЧАЙШИЙ ВЕС - до 61 кг)
    // =========================================================================
    {
        id: "merab_dvalishvili",
        name: "Merab Dvalishvili",
        nickname: "The Machine",
        division: "Bantamweight",
        rank: "C",
        record: "18-4-0",
        sherdog: { ko: 3, sub: 1, dec: 14, lossesKo: 0, lossesSub: 1, lossesDec: 3 },
        ufcStats: { slpm: 4.50, strAcc: 41, sapm: 2.37, strDef: 57, tdAvg: 6.43, tdAcc: 36, tdDef: 81 },
        verdictRating: 970,
        nationality: "Georgia",
        flag: "🇬🇪",
        height: "5'6\" (168 cm)",
        reach: "68.0\" (173 cm)",
        stance: "Orthodox",
        age: 35,
        stats: { striking: 84, wrestling: 99, grappling: 92, cardio: 100, power: 76, defense: 91 },
        bio: "UFC Bantamweight Champion with an unmatched cardio pace and UFC record takedown attempts.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4294628.png&w=350&h=254"
    },
    {
        id: "petr_yan",
        name: "Petr Yan",
        nickname: "No Mercy",
        division: "Bantamweight",
        rank: 1,
        record: "17-5-0",
        sherdog: { ko: 7, sub: 1, dec: 9, lossesKo: 0, lossesSub: 0, lossesDec: 5 },
        ufcStats: { slpm: 5.03, strAcc: 53, sapm: 4.00, strDef: 62, tdAvg: 1.71, tdAcc: 52, tdDef: 85 },
        verdictRating: 940,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "5'7\" (170 cm)",
        reach: "67.0\" (170 cm)",
        stance: "Switch",
        age: 33,
        stats: { striking: 97, wrestling: 88, grappling: 82, cardio: 94, power: 88, defense: 93 },
        bio: "Former Bantamweight Champion & Master of Sport in Boxing. High-level counter-striking technician.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4307525.png&w=350&h=254"
    },
    {
        id: "sean_omalley",
        name: "Sean O'Malley",
        nickname: "Suga",
        division: "Bantamweight",
        rank: 2,
        record: "18-2-0 (1 NC)",
        sherdog: { ko: 12, sub: 1, dec: 5, lossesKo: 1, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 7.25, strAcc: 61, sapm: 3.52, strDef: 62, tdAvg: 0.45, tdAcc: 42, tdDef: 60 },
        verdictRating: 935,
        nationality: "USA",
        flag: "🇺🇸",
        height: "5'11\" (180 cm)",
        reach: "72.0\" (183 cm)",
        stance: "Switch",
        age: 31,
        stats: { striking: 97, wrestling: 65, grappling: 68, cardio: 89, power: 88, defense: 88 },
        bio: "Former Bantamweight Champion with sniper precision striking and high-octane superstar charisma.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4223297.png&w=350&h=254"
    },
    {
        id: "umar_nurmagomedov",
        name: "Umar Nurmagomedov",
        nickname: "—",
        division: "Bantamweight",
        rank: 3,
        record: "18-0-0",
        sherdog: { ko: 2, sub: 7, dec: 9, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.75, strAcc: 50, sapm: 0.56, strDef: 69, tdAvg: 4.50, tdAcc: 57, tdDef: 100 },
        verdictRating: 960,
        nationality: "Russia",
        flag: "🇷🇺",
        height: "5'8\" (173 cm)",
        reach: "69.0\" (175 cm)",
        stance: "Orthodox",
        age: 30,
        stats: { striking: 90, wrestling: 97, grappling: 95, cardio: 95, power: 80, defense: 94 },
        bio: "Undefeated contender blending dynamic Taekwondo roundhouse kicks with Dagestani grappling.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4687641.png&w=350&h=254"
    },
    {
        id: "cory_sandhagen",
        name: "Cory Sandhagen",
        nickname: "The Sandman",
        division: "Bantamweight",
        rank: 4,
        record: "17-5-0",
        sherdog: { ko: 7, sub: 3, dec: 7, lossesKo: 0, lossesSub: 1, lossesDec: 4 },
        ufcStats: { slpm: 5.33, strAcc: 44, sapm: 3.40, strDef: 57, tdAvg: 1.36, tdAcc: 33, tdDef: 64 },
        verdictRating: 915,
        nationality: "USA",
        flag: "🇺🇸",
        height: "5'11\" (180 cm)",
        reach: "70.0\" (178 cm)",
        stance: "Switch",
        age: 34,
        stats: { striking: 94, wrestling: 85, grappling: 84, cardio: 95, power: 84, defense: 88 },
        bio: "Creative switch-stance striker famous for flying knees and evolving wrestling additions.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3920950.png&w=350&h=254"
    },

    // =========================================================================
    // FLYWEIGHT (НАИЛЕГЧАЙШИЙ ВЕС - до 57 кг)
    // =========================================================================
    {
        id: "alexandre_pantoja",
        name: "Alexandre Pantoja",
        nickname: "The Cannibal",
        division: "Flyweight",
        rank: "C",
        record: "28-5-0",
        sherdog: { ko: 8, sub: 10, dec: 10, lossesKo: 0, lossesSub: 0, lossesDec: 5 },
        ufcStats: { slpm: 4.32, strAcc: 48, sapm: 3.80, strDef: 52, tdAvg: 2.20, tdAcc: 40, tdDef: 67 },
        verdictRating: 950,
        nationality: "Brazil",
        flag: "🇧🇷",
        height: "5'5\" (165 cm)",
        reach: "68.0\" (173 cm)",
        stance: "Orthodox",
        age: 36,
        stats: { striking: 84, wrestling: 87, grappling: 96, cardio: 94, power: 80, defense: 86 },
        bio: "UFC Flyweight Champion. Ferocious scrambling grappler with non-stop submission hunting.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3990666.png&w=350&h=254"
    },
    {
        id: "brandon_moreno",
        name: "Brandon Moreno",
        nickname: "The Assassin Baby",
        division: "Flyweight",
        rank: 2,
        record: "21-8-2",
        sherdog: { ko: 5, sub: 11, dec: 5, lossesKo: 0, lossesSub: 0, lossesDec: 8 },
        ufcStats: { slpm: 3.80, strAcc: 42, sapm: 3.40, strDef: 56, tdAvg: 1.73, tdAcc: 44, tdDef: 64 },
        verdictRating: 925,
        nationality: "Mexico",
        flag: "🇲🇽",
        height: "5'7\" (170 cm)",
        reach: "70.0\" (178 cm)",
        stance: "Orthodox",
        age: 32,
        stats: { striking: 91, wrestling: 82, grappling: 90, cardio: 94, power: 78, defense: 88 },
        bio: "Two-time Flyweight Champion. First Mexican-born champion in UFC history with sharp boxing.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3947475.png&w=350&h=254"
    },
    {
        id: "kai_kara_france",
        name: "Kai Kara-France",
        nickname: "Don't Blink",
        division: "Flyweight",
        rank: 4,
        record: "25-11-0 (1 NC)",
        sherdog: { ko: 12, sub: 3, dec: 10, lossesKo: 3, lossesSub: 3, lossesDec: 5 },
        ufcStats: { slpm: 4.57, strAcc: 40, sapm: 3.57, strDef: 65, tdAvg: 0.43, tdAcc: 25, tdDef: 88 },
        verdictRating: 890,
        nationality: "New Zealand",
        flag: "🇳🇿",
        height: "5'4\" (163 cm)",
        reach: "69.0\" (175 cm)",
        stance: "Orthodox",
        age: 33,
        stats: { striking: 92, wrestling: 78, grappling: 72, cardio: 90, power: 89, defense: 85 },
        bio: "City Kickboxing power puncher with explosive overhand right KO threat.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3902123.png&w=350&h=254"
    },
    {
        id: "tatsuro_taira",
        name: "Tatsuro Taira",
        nickname: "—",
        division: "Flyweight",
        rank: 5,
        record: "16-1-0",
        sherdog: { ko: 5, sub: 7, dec: 4, lossesKo: 0, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 3.56, strAcc: 54, sapm: 2.10, strDef: 50, tdAvg: 2.12, tdAcc: 45, tdDef: 70 },
        verdictRating: 905,
        nationality: "Japan",
        flag: "🇯🇵",
        height: "5'7\" (170 cm)",
        reach: "70.0\" (178 cm)",
        stance: "Orthodox",
        age: 26,
        stats: { striking: 83, wrestling: 90, grappling: 94, cardio: 91, power: 76, defense: 87 },
        bio: "Japanese grappling prodigy with body triangle back-mount control.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4898146.png&w=350&h=254"
    },

    // =========================================================================
    // WOMEN'S DIVISIONS (ЖЕНСКИЕ ДИВИЗИОНЫ)
    // =========================================================================
    {
        id: "zhang_weili",
        name: "Zhang Weili",
        nickname: "Magnum",
        division: "Strawweight",
        rank: "C",
        record: "25-3-0",
        sherdog: { ko: 11, sub: 8, dec: 6, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 5.94, strAcc: 51, sapm: 3.44, strDef: 53, tdAvg: 2.29, tdAcc: 42, tdDef: 66 },
        verdictRating: 965,
        nationality: "China",
        flag: "🇨🇳",
        height: "5'4\" (163 cm)",
        reach: "63.0\" (160 cm)",
        stance: "Switch",
        age: 36,
        stats: { striking: 95, wrestling: 92, grappling: 90, cardio: 96, power: 93, defense: 90 },
        bio: "Two-time UFC Women's Strawweight Champion. Explosive Sanda kickboxer with heavy power and wrestling.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4389998.png&w=350&h=254"
    },
    {
        id: "valentina_shevchenko",
        name: "Valentina Shevchenko",
        nickname: "Bullet",
        division: "Women's Flyweight",
        rank: "C",
        record: "24-4-1",
        sherdog: { ko: 8, sub: 7, dec: 9, lossesKo: 1, lossesSub: 1, lossesDec: 2 },
        ufcStats: { slpm: 3.29, strAcc: 52, sapm: 1.86, strDef: 63, tdAvg: 2.56, tdAcc: 63, tdDef: 71 },
        verdictRating: 975,
        nationality: "Kyrgyzstan / Peru",
        flag: "🇰🇬",
        height: "5'5\" (165 cm)",
        reach: "67.0\" (170 cm)",
        stance: "Southpaw",
        age: 38,
        stats: { striking: 97, wrestling: 91, grappling: 89, cardio: 97, power: 86, defense: 96 },
        bio: "UFC Women's Flyweight Champion & 17-time World Muay Thai champion.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3902127.png&w=350&h=254"
    },
    {
        id: "julianna_pena",
        name: "Julianna Peña",
        nickname: "The Venezuelan Vixen",
        division: "Women's Bantamweight",
        rank: "C",
        record: "12-5-0",
        sherdog: { ko: 3, sub: 5, dec: 4, lossesKo: 1, lossesSub: 2, lossesDec: 2 },
        ufcStats: { slpm: 3.30, strAcc: 47, sapm: 2.50, strDef: 50, tdAvg: 2.10, tdAcc: 54, tdDef: 33 },
        verdictRating: 900,
        nationality: "USA",
        flag: "🇺🇸",
        height: "5'6\" (168 cm)",
        reach: "69.0\" (175 cm)",
        stance: "Orthodox",
        age: 36,
        stats: { striking: 82, wrestling: 88, grappling: 86, cardio: 92, power: 80, defense: 83 },
        bio: "UFC Women's Bantamweight Champion. Known for shock submission victory over Amanda Nunes.",
        image: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3026343.png&w=350&h=254"
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = fighters;
}
