import sys
import os

full_fighters_code = '''const fighters = [

    // =========================================================================
    // HEAVYWEIGHT (ТЯЖЕЛЫЙ ВЕС)
    // =========================================================================
    {
        id: "tom_aspinall",
        name: "Tom Aspinall",
        nickname: "—",
        division: "Heavyweight",
        rank: "C",
        record: "15-3-0",
        sherdog: { ko: 11, sub: 3, dec: 1, lossesKo: 1, lossesSub: 1, lossesDec: 1 },
        ufcStats: { slpm: 7.72, strAcc: 66, sapm: 2.77, strDef: 65, tdAvg: 2.30, tdAcc: 100, tdDef: 100 },
        nationality: "UK", flag: "🇬🇧",
        height: "6'5\" (196 cm)", reach: "78.0\" (198 cm)", stance: "Orthodox", age: 33,
        stats: { striking: 95, wrestling: 91, grappling: 93, cardio: 92, power: 98, defense: 90 },
        bio: "Действующий чемпион UFC в тяжелом весе. Невероятная скорость, нокаутирующая мощь и черный пояс по бразильскому джиу-джитсу.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-04/ASPINALL_TOM_L_BELT.png",
        fightHistory: [
            { result: "Победа", record: "15-3", opponent: "Сергей Павлович", oppFlag: "🇷🇺", method: "KO (удары)", event: "UFC 295", date: "11 ноя 2023", round: 1, time: "0:52", location: "Нью-Йорк, США", note: "Завоевал временный титул UFC в тяжелом весе; Выступление вечера" },
            { result: "Победа", record: "14-3", opponent: "Марцин Тыбура", oppFlag: "🇵🇱", method: "TKO (удары)", event: "UFC Fight Night 224", date: "22 июл 2023", round: 1, time: "0:38", location: "Лондон, Великобритания", note: "Выступление вечера" },
            { result: "Поражение", record: "13-3", opponent: "Кёртис Блэйдс", oppFlag: "🇺🇸", method: "TKO (травма колена)", event: "UFC Fight Night 208", date: "23 июл 2022", round: 1, time: "0:15", location: "Лондон, Великобритания", note: "" },
            { result: "Победа", record: "13-2", opponent: "Александр Волков", oppFlag: "🇷🇺", method: "Сдача (рычаг локтя)", event: "UFC Fight Night 204", date: "19 мар 2022", round: 1, time: "3:45", location: "Лондон, Великобритания", note: "Выступление вечера" },
            { result: "Победа", record: "12-2", opponent: "Сергей Спивак", oppFlag: "🇲🇩", method: "TKO (удары)", event: "UFC Fight Night 191", date: "4 сен 2021", round: 1, time: "2:30", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "11-2", opponent: "Андрей Орловский", oppFlag: "🇧🇾", method: "Сдача (удушение сзади)", event: "UFC Fight Night 185", date: "20 фев 2021", round: 2, time: "1:09", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "10-2", opponent: "Алан Бодо", oppFlag: "🇫🇷", method: "TKO (удары)", event: "UFC Fight Night 179", date: "10 окт 2020", round: 1, time: "1:35", location: "Абу-Даби, ОАЭ", note: "" },
            { result: "Победа", record: "9-2", opponent: "Джейк Кольер", oppFlag: "🇺🇸", method: "TKO (удары)", event: "UFC on ESPN 14", date: "25 июл 2020", round: 1, time: "0:45", location: "Абу-Даби, ОАЭ", note: "Дебют в UFC; Выступление вечера" },
            { result: "Победа", record: "8-2", opponent: "Микаэль Бен Хамуда", oppFlag: "🇫🇷", method: "TKO (удары)", event: "Cage Warriors 107", date: "28 сен 2019", round: 1, time: "0:56", location: "Ливерпуль, Великобритания", note: "" },
            { result: "Победа", record: "7-2", opponent: "Софьян Букишу", oppFlag: "🇫🇷", method: "TKO (травма ноги)", event: "Cage Warriors 101", date: "16 фев 2019", round: 1, time: "1:21", location: "Ливерпуль, Великобритания", note: "" },
            { result: "Победа", record: "6-2", opponent: "Камил Базеляк", oppFlag: "🇵🇱", method: "KO (удар)", event: "Full Contact Contender 16", date: "18 июн 2016", round: 1, time: "1:16", location: "Болтон, Великобритания", note: "" },
            { result: "Поражение", record: "5-2", opponent: "Лукаш Паржобец", oppFlag: "🇵🇱", method: "Дисквалификация", event: "BAMMA 25", date: "14 май 2016", round: 1, time: "1:45", location: "Бирмингем, Великобритания", note: "" },
            { result: "Победа", record: "5-1", opponent: "Адриан Рускал", oppFlag: "🇵🇱", method: "TKO (удары)", event: "Full Contact Contender 15", date: "5 мар 2016", round: 1, time: "1:05", location: "Болтон, Великобритания", note: "" },
            { result: "Поражение", record: "4-1", opponent: "Стюарт Остин", oppFlag: "🇬🇧", method: "Сдача (каблук)", event: "BAMMA 21", date: "13 июн 2015", round: 2, time: "3:59", location: "Бирмингем, Великобритания", note: "" },
            { result: "Победа", record: "4-0", opponent: "Сатиш Джамай", oppFlag: "🇳🇱", method: "TKO (удары)", event: "BAMMA 19", date: "28 мар 2015", round: 1, time: "0:09", location: "Blackpool, Великобритания", note: "" },
            { result: "Победа", record: "3-0", opponent: "Рики Кинг", oppFlag: "🇬🇧", method: "Сдача (скручивание пятки)", event: "BAMMA 18", date: "21 фев 2015", round: 1, time: "0:49", location: "Вулверхэмптон, Великобритания", note: "" },
            { result: "Победа", record: "2-0", opponent: "Джон Маккарти", oppFlag: "🇮🇪", method: "TKO (удары)", event: "MMA Ego 1", date: "13 дек 2014", round: 1, time: "1:36", location: "Манчестер, Великобритания", note: "" },
            { result: "Победа", record: "1-0", opponent: "Михал Пищек", oppFlag: "🇵🇱", method: "TKO (удары)", event: "MMA Maturation 1", date: "1 мар 2014", round: 1, time: "0:15", location: "Рексем, Уэльс", note: "Первый бой в профессиональном ММА" }
        ]
    },
    {
        id: "jon_jones",
        name: "Jon Jones",
        nickname: "Bones",
        division: "Heavyweight",
        rank: 1,
        record: "27-1-0 (1 NC)",
        sherdog: { ko: 10, sub: 7, dec: 10, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.30, strAcc: 57, sapm: 2.22, strDef: 64, tdAvg: 1.85, tdAcc: 45, tdDef: 95 },
        nationality: "USA", flag: "🇺🇸",
        height: "6'4\" (193 cm)", reach: "84.5\" (215 cm)", stance: "Orthodox", age: 38,
        stats: { striking: 88, wrestling: 97, grappling: 93, cardio: 91, power: 86, defense: 96 },
        bio: "Бывший многолетний чемпион UFC в полутяжелом весе и бывший чемпион в тяжелом весе. Один из величайших бойцов в истории ММА.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-03/JONES_JON_L.png",
        fightHistory: [
            { result: "Победа", record: "27-1 (1 NC)", opponent: "Стипе Миочич", oppFlag: "🇺🇸", method: "TKO (удар ногой с разворота и удары)", event: "UFC 309", date: "16 ноя 2024", round: 3, time: "4:29", location: "Нью-Йорк, США", note: "Защитил титул чемпиона UFC в тяжелом весе; Выступление вечера" },
            { result: "Победа", record: "26-1 (1 NC)", opponent: "Сирил Ган", oppFlag: "🇫🇷", method: "Сдача (гильотина)", event: "UFC 285", date: "4 мар 2023", round: 1, time: "2:04", location: "Лас-Вегас, США", note: "Завоевал вакантный титул UFC в тяжелом весе; Выступление вечера" },
            { result: "Победа", record: "25-1 (1 NC)", opponent: "Доминик Рейес", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 247", date: "8 фев 2020", round: 5, time: "5:00", location: "Хьюстон, США", note: "Защитил титул в полутяжелом весе" },
            { result: "Победа", record: "24-1 (1 NC)", opponent: "Тиагу Сантус", oppFlag: "🇧🇷", method: "Раздельное решение", event: "UFC 239", date: "6 июл 2019", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Защитил титул в полутяжелом весе" },
            { result: "Победа", record: "23-1 (1 NC)", opponent: "Энтони Смит", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 235", date: "2 мар 2019", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Защитил титул в полутяжелом весе" },
            { result: "Победа", record: "22-1 (1 NC)", opponent: "Александр Густафссон II", oppFlag: "🇸🇪", method: "KO (удары)", event: "UFC 232", date: "29 дек 2018", round: 3, time: "2:02", location: "Инглвуд, США", note: "Завоевал вакантный титул в полутяжелом весе" },
            { result: "Не состоялся", record: "21-1 (1 NC)", opponent: "Даниэль Кормье II", oppFlag: "🇺🇸", method: "NC (аннулировано)", event: "UFC 214", date: "29 июл 2017", round: 3, time: "3:01", location: "Анахайм, США", note: "Первоначально победа Джонса KO" },
            { result: "Победа", record: "21-1", opponent: "Овинс Сен-Прё", oppFlag: "🇭🇹", method: "Единогласное решение", event: "UFC 197", date: "23 апр 2016", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Завоевал временный титул" },
            { result: "Победа", record: "20-1", opponent: "Даниэль Кормье", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 182", date: "3 янв 2015", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Защитил титул; Бой вечера" },
            { result: "Победа", record: "19-1", opponent: "Гловер Тейшейра", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC 172", date: "26 апр 2014", round: 5, time: "5:00", location: "Балтимор, США", note: "Защитил титул" },
            { result: "Победа", record: "18-1", opponent: "Александр Густафссон", oppFlag: "🇸🇪", method: "Единогласное решение", event: "UFC 165", date: "21 сен 2013", round: 5, time: "5:00", location: "Торонто, Канада", note: "Защитил титул; Бой вечера" },
            { result: "Победа", record: "17-1", opponent: "Чейл Соннен", oppFlag: "🇺🇸", method: "TKO (удары)", event: "UFC 159", date: "27 апр 2013", round: 1, time: "4:33", location: "Ньюарк, США", note: "Защитил титул" },
            { result: "Победа", record: "16-1", opponent: "Витор Белфорт", oppFlag: "🇧🇷", method: "Сдача (американа)", event: "UFC 152", date: "22 сен 2012", round: 4, time: "0:54", location: "Торонто, Канада", note: "Защитил титул" },
            { result: "Победа", record: "15-1", opponent: "Рашад Эванс", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 145", date: "21 апр 2012", round: 5, time: "5:00", location: "Атланта, США", note: "Защитил титул" },
            { result: "Победа", record: "14-1", opponent: "Лиото Мачида", oppFlag: "🇧🇷", method: "Техническая сдача (гильотина)", event: "UFC 140", date: "10 дек 2011", round: 2, time: "4:26", location: "Торонто, Канада", note: "Защитил титул; Бой вечера" },
            { result: "Победа", record: "13-1", opponent: "Квитон Джексон", oppFlag: "🇺🇸", method: "Сдача (удушение сзади)", event: "UFC 135", date: "24 сен 2011", round: 4, time: "1:14", location: "Денвер, США", note: "Защитил титул; Бой вечера" },
            { result: "Победа", record: "12-1", opponent: "Маурисиу Руа", oppFlag: "🇧🇷", method: "TKO (удары)", event: "UFC 128", date: "19 мар 2011", round: 3, time: "2:37", location: "Ньюарк, США", note: "Самый молодой чемпион UFC в истории (23 года)" },
            { result: "Победа", record: "11-1", opponent: "Райан Бейдер", oppFlag: "🇺🇸", method: "Сдача (гильотина)", event: "UFC 126", date: "5 фев 2011", round: 2, time: "4:20", location: "Лас-Вегас, США", note: "Прием вечера" },
            { result: "Победа", record: "10-1", opponent: "Владимир Матюшенко", oppFlag: "🇧🇾", method: "TKO (удары локтями)", event: "UFC Live 2", date: "1 авг 2010", round: 1, time: "1:52", location: "Сан-Диего, США", note: "" },
            { result: "Победа", record: "9-1", opponent: "Брэндон Вера", oppFlag: "🇵🇭", method: "TKO (удары)", event: "UFC Live 1", date: "21 мар 2010", round: 1, time: "3:19", location: "Брумфилд, США", note: "Нокаут вечера" },
            { result: "Поражение", record: "8-1", opponent: "Мэтт Хэмилл", oppFlag: "🇺🇸", method: "Дисквалификация (локти 12-6)", event: "TUF 10 Finale", date: "5 дек 2009", round: 1, time: "4:14", location: "Лас-Вегас, США", note: "Дисквалификация из-за локтей 12-6" },
            { result: "Победа", record: "8-0", opponent: "Стефан Боннар", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 94", date: "31 янв 2009", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "7-0", opponent: "Андре Гусман", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC 87", date: "9 авг 2008", round: 3, time: "5:00", location: "Миннеаполис, США", note: "Дебют в UFC" },
            { result: "Победа", record: "6-0", opponent: "Мойзес Габин", oppFlag: "🇺🇸", method: "TKO (удары)", event: "BCC 2", date: "12 июл 2008", round: 2, time: "1:58", location: "Массачусетс, США", note: "" },
            { result: "Победа", record: "5-0", opponent: "Паркер Портер", oppFlag: "🇺🇸", method: "KO (удар)", event: "WCF 3", date: "20 июн 2008", round: 1, time: "0:36", location: "Массачусетс, США", note: "" },
            { result: "Победа", record: "4-0", opponent: "Райан Верретт", oppFlag: "🇺🇸", method: "TKO (удары)", event: "USFL 3", date: "9 май 2008", round: 1, time: "2:58", location: "Коннектикут, США", note: "" },
            { result: "Победа", record: "3-0", opponent: "Энтони Пина", oppFlag: "🇺🇸", method: "Сдача (гильотина)", event: "Ice Fighter", date: "25 апр 2008", round: 1, time: "1:15", location: "Массачусетс, США", note: "" },
            { result: "Победа", record: "2-0", opponent: "Карлос Эдуардо", oppFlag: "🇧🇷", method: "KO (удары)", event: "BCC 1", date: "19 апр 2008", round: 1, time: "0:24", location: "Массачусетс, США", note: "" },
            { result: "Победа", record: "1-0", opponent: "Брэд Бернард", oppFlag: "🇺🇸", method: "TKO (удары)", event: "FFP: Untamed 20", date: "12 апр 2008", round: 1, time: "1:32", location: "Массачусетс, США", note: "Дебют в профессиональном ММА" }
        ]
    },

    // =========================================================================
    // WELTERWEIGHT & MIDDLEWEIGHT (НИК ДИАС & ЗВЕЗДЫ ВЕСОВ)
    // =========================================================================
    {
        id: "nick_diaz",
        name: "Nick Diaz",
        nickname: "Diablo",
        division: "Welterweight",
        rank: 15,
        record: "26-10-0 (2 NC)",
        sherdog: { ko: 13, sub: 8, dec: 5, lossesKo: 3, lossesSub: 0, lossesDec: 7 },
        ufcStats: { slpm: 5.43, strAcc: 45, sapm: 3.76, strDef: 62, tdAvg: 0.81, tdAcc: 33, tdDef: 61 },
        nationality: "USA", flag: "🇺🇸",
        height: "6'1\" (185 cm)", reach: "76.0\" (193 cm)", stance: "Southpaw", age: 42,
        stats: { striking: 93, wrestling: 68, grappling: 90, cardio: 99, power: 82, defense: 80 },
        bio: "Легенда ММА из Стоктона. Бывший чемпион Strikeforce в полусреднем весе, претендент на титул UFC. Мастер BJJ и бесконечного объемного бокса.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2021-09/DIAZ_NICK_L_09-25.png",
        fightHistory: [
            { result: "Поражение", record: "26-10 (2 NC)", opponent: "Робби Лоулер II", oppFlag: "🇺🇸", method: "TKO (отказ от продолжения)", event: "UFC 266", date: "25 сен 2021", round: 3, time: "0:44", location: "Лас-Вегас, США", note: "Бой в среднем весе" },
            { result: "Не состоялся", record: "26-9 (2 NC)", opponent: "Андерсон Силва", oppFlag: "🇧🇷", method: "NC (результат аннулирован)", event: "UFC 183", date: "31 янв 2015", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Первоначально победа Силвы решением" },
            { result: "Поражение", record: "26-9 (1 NC)", opponent: "Жорж Сен-Пьер", oppFlag: "🇨🇦", method: "Единогласное решение", event: "UFC 158", date: "16 мар 2013", round: 5, time: "5:00", location: "Монреаль, Канада", note: "Бой за титул чемпиона UFC в полусреднем весе" },
            { result: "Поражение", record: "26-8 (1 NC)", opponent: "Карлос Кондит", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 143", date: "4 фев 2012", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Бой за временный титул UFC в полусреднем весе" },
            { result: "Победа", record: "26-7 (1 NC)", opponent: "Би Джей Пенн", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 137", date: "29 окт 2011", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Победа", record: "25-7 (1 NC)", opponent: "Пол Дейли", oppFlag: "🇬🇧", method: "TKO (удары)", event: "Strikeforce: Diaz vs. Daley", date: "9 апр 2011", round: 1, time: "4:57", location: "Сан-Диего, США", note: "Защитил титул Strikeforce в полусреднем весе" },
            { result: "Победа", record: "24-7 (1 NC)", opponent: "Евангелиста Сантос", oppFlag: "🇧🇷", method: "Сдача (рычаг локтя)", event: "Strikeforce: Diaz vs. Cyborg", date: "29 янв 2011", round: 2, time: "4:50", location: "Сан-Хосе, США", note: "Защитил титул Strikeforce" },
            { result: "Победа", record: "23-7 (1 NC)", opponent: "К. Дж. Нунс II", oppFlag: "🇺🇸", method: "Единогласное решение", event: "Strikeforce: Diaz vs. Noons II", date: "9 окт 2010", round: 5, time: "5:00", location: "Сан-Хосе, США", note: "Защитил титул Strikeforce" },
            { result: "Победа", record: "22-7 (1 NC)", opponent: "Хаято Сакураи", oppFlag: "🇯🇵", method: "Сдача (рычаг локтя)", event: "DREAM 14", date: "8 май 2010", round: 1, time: "3:54", location: "Сайтама, Япония", note: "" },
            { result: "Победа", record: "21-7 (1 NC)", opponent: "Мариус Жаромскис", oppFlag: "🇱🇹", method: "TKO (удары)", event: "Strikeforce: Miami", date: "30 янв 2010", round: 1, time: "4:38", location: "Sunrise, США", note: "Завоевал первый титул Strikeforce в полусреднем весе" },
            { result: "Победа", record: "20-7 (1 NC)", opponent: "Скотт Смит", oppFlag: "🇺🇸", method: "Сдача (удушение сзади)", event: "Strikeforce: Lawler vs. Shields", date: "6 июн 2009", round: 3, time: "1:41", location: "Сент-Луис, США", note: "" },
            { result: "Победа", record: "19-7 (1 NC)", opponent: "Фрэнк Шемрок", oppFlag: "🇺🇸", method: "TKO (удары)", event: "Strikeforce: Shamrock vs. Diaz", date: "11 апр 2009", round: 2, time: "3:57", location: "Сан-Хосе, США", note: "Главное событие вечера" },
            { result: "Победа", record: "18-7 (1 NC)", opponent: "Томас Денни", oppFlag: "🇺🇸", method: "TKO (удары)", event: "EliteXC: Unfinished Business", date: "26 июл 2008", round: 2, time: "0:30", location: "Стоктон, США", note: "" },
            { result: "Победа", record: "17-7 (1 NC)", opponent: "Кацуя Иноуэ", oppFlag: "🇯🇵", method: "TKO (остановка углом)", event: "DREAM 3", date: "11 май 2008", round: 1, time: "6:45", location: "Сайтама, Япония", note: "" },
            { result: "Поражение", record: "16-7 (1 NC)", opponent: "К. Дж. Нунс", oppFlag: "🇺🇸", method: "TKO (рассечение)", event: "EliteXC: Renegade", date: "10 ноя 2007", round: 1, time: "5:00", location: "Корпус-Кристи, США", note: "Бой за титул EliteXC в легком весе" },
            { result: "Победа", record: "16-6 (1 NC)", opponent: "Майк Айна", oppFlag: "🇺🇸", method: "Раздельное решение", event: "EliteXC: Hawaii", date: "15 сен 2007", round: 3, time: "5:00", location: "Гонолулу, США", note: "" },
            { result: "Не состоялся", record: "15-6 (1 NC)", opponent: "Таканори Гоми", oppFlag: "🇯🇵", method: "NC (аннулировано)", event: "PRIDE 33", date: "24 фев 2007", round: 2, time: "1:46", location: "Лас-Вегас, США", note: "Первоначально победа Диаса удушением гогоплата" },
            { result: "Победа", record: "15-6", opponent: "Тацуя Кавадзири", oppFlag: "🇯🇵", method: "Сдача (рычаг локтя)", event: "PRIDE Shockwave 2006", date: "31 дек 2006", round: 1, time: "4:37", location: "Сайтама, Япония", note: "" },
            { result: "Победа", record: "14-6", opponent: "Глейсон Тибау", oppFlag: "🇧🇷", method: "TKO (удары)", event: "UFC 65", date: "18 ноя 2006", round: 2, time: "2:27", location: "Скрамтон, США", note: "" },
            { result: "Победа", record: "13-6", opponent: "Джош Нир", oppFlag: "🇺🇸", method: "Сдача (кимура)", event: "UFC 62", date: "26 авг 2006", round: 3, time: "1:42", location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Поражение", record: "12-6", opponent: "Шон Шерк", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 59", date: "15 апр 2006", round: 3, time: "5:00", location: "Анахайм, США", note: "" },
            { result: "Поражение", record: "12-5", opponent: "Джо Риггс", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 57", date: "4 фев 2006", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Поражение", record: "12-4", opponent: "Диего Санчес", oppFlag: "🇺🇸", method: "Единогласное решение", event: "TUF 2 Finale", date: "5 ноя 2005", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "12-3", opponent: "Кодзи Оиси", oppFlag: "🇯🇵", method: "KO (удары)", event: "UFC 53", date: "4 июн 2005", round: 1, time: "1:24", location: "Атлантик-Сити, США", note: "" },
            { result: "Победа", record: "11-3", opponent: "Дрю Фикетт", oppFlag: "🇺🇸", method: "TKO (удары)", event: "UFC 51", date: "5 фев 2005", round: 1, time: "4:40", location: "Лас-Вегас, США", note: "" },
            { result: "Поражение", record: "10-3", opponent: "Каро Паризян", oppFlag: "🇦🇲", method: "Раздельное решение", event: "UFC 49", date: "21 авг 2004", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "10-2", opponent: "Робби Лоулер", oppFlag: "🇺🇸", method: "KO (удар)", event: "UFC 47", date: "2 апр 2004", round: 2, time: "1:31", location: "Лас-Вегас, США", note: "Легендарный нокаут" },
            { result: "Победа", record: "9-2", opponent: "Джереми Джексон III", oppFlag: "🇺🇸", method: "Сдача (рычаг локтя)", event: "UFC 44", date: "26 сен 2003", round: 3, time: "2:04", location: "Лас-Вегас, США", note: "Дебют в UFC" },
            { result: "Победа", record: "8-2", opponent: "Джереми Джексон II", oppFlag: "🇺🇸", method: "TKO (удары)", event: "IFC: Warriors Challenge 18", date: "19 июл 2003", round: 1, time: "4:33", location: "Калифорния, США", note: "Завоевал титул IFC US в полусреднем весе" },
            { result: "Поражение", record: "7-2", opponent: "Джереми Джексон", oppFlag: "🇺🇸", method: "TKO (удары)", event: "IFC: WC 17", date: "27 мар 2003", round: 1, time: "4:23", location: "Калифорния, США", note: "" },
            { result: "Победа", record: "7-1", opponent: "Джо Херли", oppFlag: "🇺🇸", method: "Единогласное решение", event: "WEC 5", date: "14 дек 2002", round: 3, time: "5:00", location: "Калифорния, США", note: "Завоевал первый титул WEC в полусреднем весе" },
            { result: "Победа", record: "6-1", opponent: "Адам Линн", oppFlag: "🇺🇸", method: "Сдача (рычаг локтя)", event: "UA 4: KING OF THE MOUNTAIN", date: "28 сен 2002", round: 1, time: "2:51", location: "Калифорния, США", note: "" },
            { result: "Победа", record: "5-1", opponent: "Харрис Сармиенто", oppFlag: "🇵🇭", method: "Единогласное решение", event: "Warriors Challenge 17", date: "13 июл 2002", round: 3, time: "5:00", location: "Калифорния, США", note: "" },
            { result: "Поражение", record: "4-1", opponent: "Куниёси Хиронака", oppFlag: "🇯🇵", method: "Раздельное решение", event: "Shooto: Treasure Hunt 6", date: "11 май 2002", round: 3, time: "5:00", location: "Токио, Япония", note: "" },
            { result: "Победа", record: "4-0", opponent: "Крис Лайтл", oppFlag: "🇺🇸", method: "Единогласное решение", event: "IFC: Warriors Challenge 15", date: "27 апр 2002", round: 3, time: "5:00", location: "Калифорния, США", note: "Завоевал титул IFC Welterweight" },
            { result: "Победа", record: "3-0", opponent: "Майк Вик", oppFlag: "🇺🇸", method: "TKO (удары)", event: "Warmap 1", date: "23 мар 2002", round: 1, time: "3:43", location: "Калифорния, США", note: "" },
            { result: "Победа", record: "2-0", opponent: "Джесси Лиуа", oppFlag: "🇺🇸", method: "Сдача (рычаг локтя)", event: "IFC: WC 14", date: "9 фев 2002", round: 1, time: "4:43", location: "Калифорния, США", note: "" },
            { result: "Победа", record: "1-0", opponent: "Джексон Болт", oppFlag: "🇺🇸", method: "Сдача (треугольник)", event: "IFC: WC 13", date: "31 авг 2001", round: 1, time: "0:15", location: "Калифорния, США", note: "Дебют Ника Диаса в профессиональном ММА" }
        ]
    },
    {
        id: "belal_muhammad",
        name: "Belal Muhammad",
        nickname: "Remember the Name",
        division: "Welterweight",
        rank: "C",
        record: "24-3-0 (1 NC)",
        sherdog: { ko: 5, sub: 1, dec: 18, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 4.29, strAcc: 43, sapm: 3.64, strDef: 57, tdAvg: 2.47, tdAcc: 35, tdDef: 92 },
        nationality: "USA / Palestine", flag: "🇵🇸",
        height: "5'11\" (180 cm)", reach: "72.0\" (183 cm)", stance: "Orthodox", age: 38,
        stats: { striking: 87, wrestling: 96, grappling: 90, cardio: 99, power: 80, defense: 94 },
        bio: "Действующий чемпион UFC в полусреднем весе. Невероятный темп, непрерывный прессинг и высочайшая выносливость.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-07/MUHAMMAD_BELAL_L_BELT_07-27-2024.png",
        fightHistory: [
            { result: "Победа", record: "24-3 (1 NC)", opponent: "Леон Эдвардс", oppFlag: "🇬🇧", method: "Единогласное решение", event: "UFC 304", date: "27 июл 2024", round: 5, time: "5:00", location: "Манчестер, Великобритания", note: "Завоевал титул чемпиона UFC в полусреднем весе" },
            { result: "Победа", record: "23-3 (1 NC)", opponent: "Гилберт Бернс", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC 288", date: "6 май 2023", round: 5, time: "5:00", location: "Ньюарк, США", note: "" },
            { result: "Победа", record: "22-3 (1 NC)", opponent: "Шон Брэди", oppFlag: "🇺🇸", method: "TKO (удары)", event: "UFC 280", date: "22 окт 2022", round: 2, time: "4:47", location: "Абу-Даби, ОАЭ", note: "Выступление вечера" },
            { result: "Победа", record: "21-3 (1 NC)", opponent: "Висенте Луке II", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC on ESPN 34", date: "16 апр 2022", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "20-3 (1 NC)", opponent: "Стивен Томпсон", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC Fight Night 199", date: "18 дек 2021", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "19-3 (1 NC)", opponent: "Демиан Майя", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC 263", date: "12 июн 2021", round: 3, time: "5:00", location: "Глендейл, США", note: "" },
            { result: "Не состоялся", record: "18-3 (1 NC)", opponent: "Леон Эдвардс", oppFlag: "🇬🇧", method: "NC (тычок в глаз)", event: "UFC Fight Night 187", date: "13 мар 2021", round: 2, time: "0:18", location: "Лас-Вегас, США", note: "Остановка врачом" },
            { result: "Победа", record: "18-3", opponent: "Диего Лима", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC 258", date: "13 фев 2021", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "17-3", opponent: "Лайман Гуд", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC on ESPN 11", date: "20 июн 2020", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "16-3", opponent: "Такаси Сато", oppFlag: "🇯🇵", method: "Сдача (удушение сзади)", event: "UFC 242", date: "7 сен 2019", round: 3, time: "1:55", location: "Абу-Даби, ОАЭ", note: "Выступление вечера" },
            { result: "Победа", record: "15-3", opponent: "Кёртис Миллендер", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 236", date: "13 апр 2019", round: 3, time: "5:00", location: "Атланта, США", note: "" },
            { result: "Поражение", record: "14-3", opponent: "Джефф Нил", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC Fight Night 143", date: "19 янв 2019", round: 3, time: "5:00", location: "Бруклин, США", note: "" },
            { result: "Победа", record: "14-2", opponent: "Чен Сон Кан", oppFlag: "🇰🇷", method: "Единогласное решение", event: "UFC Fight Night 131", date: "1 июн 2018", round: 3, time: "5:00", location: "Ютика, США", note: "" },
            { result: "Победа", record: "13-2", opponent: "Тим Means", oppFlag: "🇺🇸", method: "Раздельное решение", event: "UFC Fight Night 121", date: "19 ноя 2017", round: 3, time: "5:00", location: "Сидней, Австралия", note: "" },
            { result: "Победа", record: "12-2", opponent: "Джордан Мейн", oppFlag: "🇨🇦", method: "Единогласное решение", event: "UFC 213", date: "8 июл 2017", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Поражение", record: "11-2", opponent: "Висенте Луке", oppFlag: "🇧🇷", method: "KO (удары)", event: "UFC 205", date: "12 ноя 2016", round: 1, time: "1:19", location: "Нью-Йорк, США", note: "" },
            { result: "Победа", record: "11-1", opponent: "Аугусто Монтаньо", oppFlag: "🇲🇽", method: "TKO (удары)", event: "UFC Fight Night 94", date: "17 сен 2016", round: 3, time: "4:19", location: "Идальго, США", note: "" },
            { result: "Поражение", record: "10-1", opponent: "Алан Жубан", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC Fight Night 90", date: "7 июл 2016", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "Дебют в UFC; Бой вечера" },
            { result: "Победа", record: "10-0", opponent: "Стив Карл", oppFlag: "🇺🇸", method: "TKO (удары)", event: "Titan FC 38", date: "30 апр 2016", round: 4, time: "4:07", location: "Майами, США", note: "Завоевал титул Titan FC в полусреднем весе" },
            { result: "Победа", record: "9-0", opponent: "Зейн Камака", oppFlag: "🇺🇸", method: "Единогласное решение", event: "Titan FC 35", date: "19 сен 2015", round: 3, time: "5:00", location: "Вашингтон, США", note: "" },
            { result: "Победа", record: "8-0", opponent: "Крис Кёртис", oppFlag: "🇺🇸", method: "Единогласное решение", event: "Hover FC 2", date: "24 июл 2015", round: 3, time: "5:00", location: "Индиана, США", note: "" },
            { result: "Победа", record: "7-0", opponent: "Кейт Джонсон", oppFlag: "🇺🇸", method: "Единогласное решение", event: "Titan FC 33", date: "20 мар 2015", round: 3, time: "5:00", location: "Мобил, США", note: "" },
            { result: "Победа", record: "6-0", opponent: "Эй Джей Мэтьюз", oppFlag: "🇺🇸", method: "Единогласное решение", event: "Bellator 112", date: "14 мар 2014", round: 3, time: "5:00", location: "Индиана, США", note: "Дебют в Bellator" },
            { result: "Победа", record: "5-0", opponent: "Гаррет Гросс", oppFlag: "🇺🇸", method: "Единогласное решение", event: "Hover FC 1", date: "7 фев 2014", round: 3, time: "5:00", location: "Индиана, США", note: "" },
            { result: "Победа", record: "4-0", opponent: "Джимми Фриц", oppFlag: "🇺🇸", method: "TKO (удары)", event: "Hover FC 1", date: "8 июн 2013", round: 2, time: "2:15", location: "Индиана, США", note: "" },
            { result: "Победа", record: "3-0", opponent: "Куинтон МакКоттрелл", oppFlag: "🇺🇸", method: "Сдача (удушение)", event: "Bellator 84", date: "14 дек 2012", round: 1, time: "3:17", location: "Индиана, США", note: "" },
            { result: "Победа", record: "2-0", opponent: "Амир Хусру", oppFlag: "🇺🇸", method: "TKO (удары)", event: "PFC 13", date: "8 июн 2012", round: 1, time: "2:25", location: "Иллинойс, США", note: "" },
            { record: "1-0", result: "Победа", opponent: "Джастин Шоу", oppFlag: "🇺🇸", method: "TKO (удары)", event: "Hover FC", date: "27 янв 2012", round: 1, time: "1:47", location: "Иллинойс, США", note: "Первый бой в профессиональном ММА" }
        ]
    },

    // =========================================================================
    // LIGHT HEAVYWEIGHT & MIDDLEWEIGHT (АЛЕКС ПЕРЕЙРА & ДРИКУС ДЮ ПЛЕССИ)
    // =========================================================================
    {
        id: "alex_pereira",
        name: "Alex Pereira",
        nickname: "Poatan",
        division: "Light Heavyweight",
        rank: "C",
        record: "12-2-0",
        sherdog: { ko: 10, sub: 0, dec: 2, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 5.23, strAcc: 63, sapm: 3.51, strDef: 51, tdAvg: 0.18, tdAcc: 100, tdDef: 70 },
        nationality: "Brazil", flag: "🇧🇷",
        height: "6'4\" (193 cm)", reach: "79.0\" (200 cm)", stance: "Orthodox", age: 38,
        stats: { striking: 99, wrestling: 68, grappling: 70, cardio: 88, power: 100, defense: 85 },
        bio: "Действующий чемпион UFC в полутяжелом весе и бывший чемпион в среднем весе. Легенда кикбоксинга Glory с убойным левым хуком.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-04/PEREIRA_ALEX_L_BELT_04-13-2024.png",
        fightHistory: [
            { result: "Победа", record: "12-2", opponent: "Халил Раунти II", oppFlag: "🇺🇸", method: "TKO (удары)", event: "UFC 307", date: "5 окт 2024", round: 4, time: "4:32", location: "Солт-Лейк-Сити, США", note: "Защитил титул в полутяжелом весе; Бой вечера" },
            { result: "Победа", record: "11-2", opponent: "Иржи Прохазка II", oppFlag: "🇨🇿", method: "TKO (удар ногой в голову и удары)", event: "UFC 303", date: "29 июн 2024", round: 2, time: "0:13", location: "Лас-Вегас, США", note: "Защитил титул в полутяжелом весе; Выступление вечера" },
            { result: "Победа", record: "10-2", opponent: "Джамахал Хилл", oppFlag: "🇺🇸", method: "KO (удар)", event: "UFC 300", date: "13 апр 2024", round: 1, time: "3:14", location: "Лас-Вегас, США", note: "Защитил титул в полутяжелом весе" },
            { result: "Победа", record: "9-2", opponent: "Иржи Прохазка", oppFlag: "🇨🇿", method: "TKO (локти)", event: "UFC 295", date: "11 ноя 2023", round: 2, time: "4:08", location: "Нью-Йорк, США", note: "Завоевал вакантный титул UFC в полутяжелом весе; Выступление вечера" },
            { result: "Победа", record: "8-2", opponent: "Ян Блахович", oppFlag: "🇵🇱", method: "Раздельное решение", event: "UFC 291", date: "29 июл 2023", round: 3, time: "5:00", location: "Солт-Лейк-Сити, США", note: "Дебют в полутяжелом весе" },
            { result: "Поражение", record: "7-2", opponent: "Исраэль Адесанья II", oppFlag: "🇳🇿", method: "KO (удары)", event: "UFC 287", date: "8 апр 2023", round: 2, time: "4:21", location: "Майами, США", note: "Потерял титул чемпиона UFC в среднем весе" },
            { result: "Победа", record: "7-1", opponent: "Исраэль Адесанья", oppFlag: "🇳🇿", method: "TKO (удары)", event: "UFC 281", date: "12 ноя 2022", round: 5, time: "2:01", location: "Нью-Йорк, США", note: "Завоевал титул чемпиона UFC в среднем весе; Выступление вечера" },
            { result: "Победа", record: "6-1", opponent: "Шон Стрикленд", oppFlag: "🇺🇸", method: "KO (удар)", event: "UFC 276", date: "2 июл 2022", round: 1, time: "2:36", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "5-1", opponent: "Бруно Силва", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC Fight Night 203", date: "12 мар 2022", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "4-1", opponent: "Андреас Михайлидис", oppFlag: "🇬🇷", method: "TKO (колено в прыжке)", event: "UFC 268", date: "6 ноя 2021", round: 2, time: "0:18", location: "Нью-Йорк, США", note: "Дебют в UFC; Выступление вечера" },
            { result: "Победа", record: "3-1", opponent: "Томас Пауэлл", oppFlag: "🇺🇸", method: "KO (удар)", event: "LFA 95", date: "20 ноя 2020", round: 1, time: "4:04", location: "Парк-Сити, США", note: "" },
            { result: "Победа", record: "2-1", opponent: "Маркус Винисиус", oppFlag: "🇧🇷", method: "TKO (удары)", event: "Jungle Fight 87", date: "21 май 2016", round: 2, time: "4:55", location: "Сан-Паулу, Бразилия", note: "" },
            { result: "Победа", record: "1-1", opponent: "Марсело Крус", oppFlag: "🇧🇷", method: "TKO (удары)", event: "Jungle Fight 85", date: "23 янв 2016", round: 1, time: "4:07", location: "Сан-Паулу, Бразилия", note: "" },
            { result: "Поражение", record: "0-1", opponent: "Quemuel Ottoni", oppFlag: "🇧🇷", method: "Сдача (удушение сзади)", event: "Jungle Fight 82", date: "24 окт 2015", round: 3, time: "2:52", location: "Сан-Паулу, Бразилия", note: "Первый профессиональный бой в ММА" }
        ]
    },
    {
        id: "dricus_du_plessis",
        name: "Dricus du Plessis",
        nickname: "Stillknocks",
        division: "Middleweight",
        rank: "C",
        record: "22-2-0",
        sherdog: { ko: 9, sub: 10, dec: 3, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 6.49, strAcc: 50, sapm: 3.79, strDef: 53, tdAvg: 3.00, tdAcc: 50, tdDef: 50 },
        nationality: "South Africa", flag: "🇿🇦",
        height: "6'1\" (185 cm)", reach: "76.0\" (193 cm)", stance: "Switch", age: 32,
        stats: { striking: 89, wrestling: 91, grappling: 88, cardio: 95, power: 94, defense: 85 },
        bio: "Действующий чемпион UFC в среднем весе. Неординарный нестандартный стиль прессинга с мощным финишем.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-01/DU_PLESSIS_DRICUS_L_BELT_01-20-2024.png",
        fightHistory: [
            { result: "Победа", record: "22-2", opponent: "Исраэль Адесанья", oppFlag: "🇳🇿", method: "Сдача (залом шеи)", event: "UFC 305", date: "17 авг 2024", round: 4, time: "3:38", location: "Перт, Австралия", note: "Защитил титул чемпиона UFC в среднем весе" },
            { result: "Победа", record: "21-2", opponent: "Шон Стрикленд", oppFlag: "🇺🇸", method: "Раздельное решение", event: "UFC 297", date: "20 янв 2024", round: 5, time: "5:00", location: "Торонто, Канада", note: "Завоевал титул чемпиона UFC в среднем весе; Бой вечера" },
            { result: "Победа", record: "20-2", opponent: "Роберт Уиттакер", oppFlag: "🇦🇺", method: "TKO (удары)", event: "UFC 290", date: "8 июл 2023", round: 2, time: "2:23", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "19-2", opponent: "Дерек Брансон", oppFlag: "🇺🇸", method: "TKO (остановка углом)", event: "UFC 285", date: "4 мар 2023", round: 2, time: "4:59", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "18-2", opponent: "Даррен Тилл", oppFlag: "🇬🇧", method: "Сдача (удушение сзади)", event: "UFC 282", date: "10 дек 2022", round: 3, time: "2:43", location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Победа", record: "17-2", opponent: "Тревин Джайлс", oppFlag: "🇺🇸", method: "KO (удары)", event: "UFC 264", date: "10 июл 2021", round: 2, time: "1:41", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "16-2", opponent: "Маркус Перес", oppFlag: "🇧🇷", method: "KO (удары)", event: "UFC Fight Night 179", date: "10 окт 2020", round: 1, time: "3:22", location: "Абу-Даби, ОАЭ", note: "Дебют в UFC" },
            { result: "Победа", record: "15-2", opponent: "Леандро Силва", oppFlag: "🇧🇷", method: "Единогласное решение", event: "KSW 50", date: "14 сен 2019", round: 3, time: "5:00", location: "Лондон, Великобритания", note: "" },
            { result: "Победа", record: "14-2", opponent: "Йоилтон Луттербах", oppFlag: "🇧🇷", method: "TKO (удары)", event: "EFC 80", date: "29 июн 2019", round: 2, time: "3:04", location: "Сибиу, Румыния", note: "" },
            { result: "Поражение", record: "13-2", opponent: "Роберто Солдич II", oppFlag: "🇭🇷", method: "KO (удары)", event: "KSW 45", date: "6 окт 2018", round: 3, time: "2:33", location: "Лондон, Великобритания", note: "Потерял титул KSW в полусреднем весе" },
            { result: "Победа", record: "13-1", opponent: "Роберто Солдич", oppFlag: "🇭🇷", method: "TKO (удары)", event: "KSW 43", date: "14 апр 2018", round: 2, time: "1:37", location: "Вроцлав, Польша", note: "Завоевал титул KSW в полусреднем весе" },
            { result: "Победа", record: "12-1", opponent: "Янник Бахати", oppFlag: "🇬🇧", method: "Сдача (гильотина)", event: "EFC 62", date: "19 авг 2017", round: 1, time: "1:30", location: "Йоханнесбург, ЮАР", note: "Завоевал титул EFC в среднем весе" },
            { result: "Победа", record: "11-1", opponent: "Хосе Да Коста", oppFlag: "🇧🇷", method: "TKO (удары)", event: "EFC 59", date: "13 май 2017", round: 1, time: "3:37", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "10-1", opponent: "Рафал Харатык", oppFlag: "🇵🇱", method: "Сдача (гильотина)", event: "EFC 56", date: "9 дек 2016", round: 2, time: "3:34", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "9-1", opponent: "Мартин ван Стейден", oppFlag: "ЮАР", method: "Сдача (гильотина)", event: "EFC 50", date: "17 июн 2016", round: 3, time: "3:59", location: "Сун-Сити, ЮАР", note: "Завоевал вакантный титул EFC в полусреднем весе" },
            { result: "Победа", record: "8-1", opponent: "Сисеко Макама", oppFlag: "ЮАР", method: "Сдача (удушение сзади)", event: "EFC 46", date: "12 дек 2015", round: 2, time: "4:02", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "7-1", opponent: "Дино Багатин", oppFlag: "ЮАР", method: "Сдача (удушение сзади)", event: "EFC 40", date: "6 июн 2015", round: 2, time: "3:33", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "6-1", opponent: "Даррен Даниэль", oppFlag: "ЮАР", method: "Сдача (гильотина)", event: "EFC 37", date: "21 фев 2015", round: 1, time: "4:50", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Поражение", record: "5-1", opponent: "Гаррет Маклеллан", oppFlag: "ЮАР", method: "Сдача (гильотина)", event: "EFC 33", date: "30 авг 2014", round: 3, time: "2:12", location: "Дурбан, ЮАР", note: "Бой за титул EFC в среднем весе" },
            { result: "Победа", record: "5-0", opponent: "Донавин Ховри", oppFlag: "ЮАР", method: "TKO (удары)", event: "EFC 27", date: "27 фев 2014", round: 2, time: "4:50", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "4-0", opponent: "Джон Де Брёйн", oppFlag: "ЮАР", method: "TKO (удары)", event: "EFC 25", date: "7 ноя 2013", round: 1, time: "3:33", location: "Капштад, ЮАР", note: "" },
            { result: "Победа", record: "3-0", opponent: "Бруно Мукалу", oppFlag: "ДР Конго", method: "Сдача (удушение)", event: "EFC 23", date: "12 сен 2013", round: 2, time: "2:34", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "2-0", opponent: "Михаэль Де Врис", oppFlag: "ЮАР", method: "Сдача (удушение)", event: "EFC 21", date: "25 июл 2013", round: 1, time: "2:23", location: "Йоханнесбург, ЮАР", note: "" },
            { result: "Победа", record: "1-0", opponent: "Тзимис Тпанидес", oppFlag: "Кипр", method: "TKO (удары)", event: "EFC 20", date: "27 июн 2013", round: 1, time: "1:18", location: "Йоханнесбург, ЮАР", note: "Первый бой в профессиональном ММА" }
        ]
    },

    // =========================================================================
    // FEATHERWEIGHT & BANTAMWEIGHT (ИЛИЯ ТОПУРИЯ & МЕРАБ ДВАЛИШВИЛИ)
    // =========================================================================
    {
        id: "ilia_topuria",
        name: "Ilia Topuria",
        nickname: "El Matador",
        division: "Featherweight",
        rank: "C",
        record: "16-0-0",
        sherdog: { ko: 6, sub: 8, dec: 2, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.40, strAcc: 46, sapm: 3.35, strDef: 65, tdAvg: 1.92, tdAcc: 56, tdDef: 92 },
        nationality: "Spain / Georgia", flag: "🇪🇸",
        height: "5'7\" (170 cm)", reach: "69.0\" (175 cm)", stance: "Orthodox", age: 29,
        stats: { striking: 96, wrestling: 89, grappling: 91, cardio: 91, power: 94, defense: 91 },
        bio: "Непобежденный действующий чемпион UFC в полулегком весе. Феноменальный бокс и греко-римская борьба.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-02/TOPURIA_ILIA_L_BELT_02-17-2024.png",
        fightHistory: [
            { result: "Победа", record: "16-0", opponent: "Макс Холлоуэй", oppFlag: "🇺🇸", method: "KO (удары)", event: "UFC 308", date: "26 окт 2024", round: 3, time: "2:30", location: "Абу-Даби, ОАЭ", note: "Защитил титул в полулегком весе; Выступление вечера" },
            { result: "Победа", record: "15-0", opponent: "Александр Волкановски", oppFlag: "🇦🇺", method: "KO (удар)", event: "UFC 298", date: "17 фев 2024", round: 2, time: "3:32", location: "Анахайм, США", note: "Завоевал титул чемпиона UFC в полулегком весе; Выступление вечера" },
            { result: "Победа", record: "14-0", opponent: "Джош Эмметт", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC on ABC 5", date: "24 июн 2023", round: 5, time: "5:00", location: "Джексонвилл, США", note: "Бой вечера" },
            { result: "Победа", record: "13-0", opponent: "Брайс Митчелл", oppFlag: "🇺🇸", method: "Сдача (ручной треугольник)", event: "UFC 282", date: "10 дек 2022", round: 2, time: "3:10", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "12-0", opponent: "Джай Герберт", oppFlag: "🇬🇧", method: "KO (удар)", event: "UFC Fight Night 204", date: "19 мар 2022", round: 2, time: "1:07", location: "Лондон, Великобритания", note: "Бой в легком весе; Выступление вечера" },
            { result: "Победа", record: "11-0", opponent: "Райан Холл", oppFlag: "🇺🇸", method: "KO (удары)", event: "UFC 264", date: "10 июл 2021", round: 1, time: "4:47", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "10-0", opponent: "Дэймон Джексон", oppFlag: "🇺🇸", method: "KO (удар)", event: "UFC on ESPN 19", date: "5 дек 2020", round: 1, time: "2:38", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "9-0", opponent: "Юссеф Залал", oppFlag: "🇲🇦", method: "Единогласное решение", event: "UFC Fight Night 179", date: "10 окт 2020", round: 3, time: "5:00", location: "Абу-Даби, ОАЭ", note: "Дебют в UFC" },
            { result: "Победа", record: "8-0", opponent: "Стивен Гонсалвес", oppFlag: "ЮАР", method: "KO (удар)", event: "Brave CF 29", date: "15 ноя 2019", round: 1, time: "3:42", location: "Гургон, Индия", note: "" },
            { result: "Победа", record: "7-0", opponent: "Луис Гомес", oppFlag: "🇪🇸", method: "Сдача (рычаг локтя)", event: "Brave CF 26", date: "7 сен 2019", round: 1, time: "1:15", location: "Богота, Колумбия", note: "" },
            { result: "Победа", record: "6-0", opponent: "Брайан Боуланд", oppFlag: "🇧🇪", method: "Техническая сдача (анаконда)", event: "Cage Warriors 94", date: "16 июн 2018", round: 1, time: "1:39", location: "Антверпен, Бельгия", note: "Бой за титул Cage Warriors Bantamweight" },
            { result: "Победа", record: "5-0", opponent: "Микаэль Замбо", oppFlag: "🇫🇷", method: "Сдача (удушение сзади)", event: "Mix Fight Events 28", date: "5 ноя 2016", round: 1, time: "3:37", location: "Валенсия, Испания", note: "" },
            { result: "Победа", record: "4-0", opponent: "Даниэль Васкес", oppFlag: "🇪🇸", method: "Сдача (анаконда)", event: "Mix Fight Events 26", date: "7 май 2016", round: 1, time: "1:50", location: "Аликанте, Испания", note: "" },
            { result: "Победа", record: "3-0", opponent: "Калин Гарсия", oppFlag: "🇪🇸", method: "Сдача (гильотина)", event: "Mix Fight Events 24", date: "25 апр 2015", round: 1, time: "1:03", location: "Валенсия, Испания", note: "" },
            { result: "Победа", record: "2-0", opponent: "Тюдор Дрокан", oppFlag: "🇲🇩", method: "Сдача (гильотина)", event: "Mix Fight Events 22", date: "12 апр 2015", round: 1, time: "1:03", location: "Валенсия, Испания", note: "" },
            { result: "Победа", record: "1-0", opponent: "Франсиско Хавьер Асприлья", oppFlag: "🇪🇸", method: "Сдача (треугольник)", event: "Mix Fight Events 17", date: "4 апр 2015", round: 1, time: "3:30", location: "Валенсия, Испания", note: "Первый бой в профессиональном ММА" }
        ]
    },
    {
        id: "merab_dvalishvili",
        name: "Merab Dvalishvili",
        nickname: "The Machine",
        division: "Bantamweight",
        rank: "C",
        record: "18-4-0",
        sherdog: { ko: 3, sub: 1, dec: 14, lossesKo: 0, lossesSub: 1, lossesDec: 3 },
        ufcStats: { slpm: 4.50, strAcc: 41, sapm: 2.37, strDef: 57, tdAvg: 6.43, tdAcc: 36, tdDef: 81 },
        nationality: "Georgia", flag: "🇬🇪",
        height: "5'6\" (168 cm)", reach: "68.0\" (173 cm)", stance: "Orthodox", age: 35,
        stats: { striking: 84, wrestling: 99, grappling: 92, cardio: 100, power: 76, defense: 91 },
        bio: "Действующий чемпион UFC в легчайшем весе. Бесконечное кардио и мировой рекорд по количеству попыток тейкдаунов.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-09/DVALISHVILI_MERAB_L_BELT_09-14-2024.png",
        fightHistory: [
            { result: "Победа", record: "18-4", opponent: "Шон О'Мэлли", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 306", date: "14 сен 2024", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Завоевал титул чемпиона UFC в легчайшем весе" },
            { result: "Победа", record: "17-4", opponent: "Генри Сехудо", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 298", date: "17 фев 2024", round: 3, time: "5:00", location: "Анахайм, США", note: "" },
            { result: "Победа", record: "16-4", opponent: "Петр Ян", oppFlag: "🇷🇺", method: "Единогласное решение", event: "UFC Fight Night 221", date: "11 мар 2023", round: 5, time: "5:00", location: "Лас-Вегас, США", note: "Установил рекорд UFC по попыткам тейкдаунов (49)" },
            { result: "Победа", record: "15-4", opponent: "Жозе Алду", oppFlag: "🇧🇷", method: "Единогласное решение", event: "UFC 278", date: "20 авг 2022", round: 3, time: "5:00", location: "Солт-Лейк-Сити, США", note: "" },
            { result: "Победа", record: "14-4", opponent: "Марлон Мораес", oppFlag: "🇧🇷", method: "TKO (удары)", event: "UFC 266", date: "25 сен 2021", round: 2, time: "4:25", location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа", record: "13-4", opponent: "Коди Стаманн", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC on ESPN 23", date: "1 май 2021", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "12-4", opponent: "Джон Додсон", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC 252", date: "15 авг 2020", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "" },
            { result: "Победа", record: "11-4", opponent: "Густаво Лопес", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC on ESPN 10", date: "13 июн 2020", round: 3, time: "5:00", location: "Лас-Вегас, США", note: "Промежуточный вес 140 фунтов" },
            { result: "Победа", record: "10-4", opponent: "Кейси Кенни", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC Fight Night 167", date: "15 фев 2020", round: 3, time: "5:00", location: "Рио-Ранчо, США", note: "" },
            { result: "Победа", record: "9-4", opponent: "Брэд Катона", oppFlag: "🇨🇦", method: "Единогласное решение", event: "UFC Fight Night 151", date: "4 май 2019", round: 3, time: "5:00", location: "Оттава, Канада", note: "" },
            { result: "Победа", record: "8-4", opponent: "Террион Уэйр", oppFlag: "🇺🇸", method: "Единогласное решение", event: "UFC Fight Night 136", date: "15 сен 2018", round: 3, time: "5:00", location: "Москва, Россия", note: "" },
            { result: "Поражение", record: "7-4", opponent: "Рик Саймон", oppFlag: "🇺🇸", method: "Техническая сдача (гильотина)", event: "UFC Fight Night 128", date: "21 апр 2018", round: 3, time: "5:00", location: "Атлантик-Сити, США", note: "Бой вечера" },
            { result: "Поражение", record: "7-3", opponent: "Фрэнки Саенс", oppFlag: "🇺🇸", method: "Раздельное решение", event: "UFC Fight Night 123", date: "9 дек 2017", round: 3, time: "5:00", location: "Фресно, США", note: "Дебют в UFC" },
            { result: "Победа", record: "7-2", opponent: "Рауфеон Стотс", oppFlag: "🇺🇸", method: "KO (бэкфист)", event: "CFFC 66", date: "5 авг 2017", round: 1, time: "0:15", location: "Атлантик-Сити, США", note: "Защитил титул CFFC Bantamweight" },
            { result: "Победа", record: "6-2", opponent: "Сukhроб Айдаров", oppFlag: "Узб", method: "Единогласное решение", event: "ROC 58", date: "24 фев 2017", round: 3, time: "5:00", location: "Атлантик-Сити, США", note: "Завоевал вакантный титул CFFC Bantamweight" },
            { result: "Победа", record: "5-2", opponent: "Пол Грант", oppFlag: "🇺🇸", method: "Единогласное решение", event: "CFFC 63", date: "18 фев 2017", round: 3, time: "5:00", location: "Атлантик-Сити, США", note: "" },
            { result: "Победа", record: "4-2", opponent: "Джеффри Тени", oppFlag: "🇺🇸", method: "Единогласное решение", event: "CFFC 60", date: "6 авг 2016", round: 3, time: "5:00", location: "Атлантик-Сити, США", note: "" },
            { result: "Победа", record: "3-2", opponent: "Мэтт Туллос", oppFlag: "🇺🇸", method: "Единогласное решение", event: "CES MMA 36", date: "10 июн 2016", round: 3, time: "5:00", location: "Линкольн, США", note: "" },
            { result: "Победа", record: "2-2", opponent: "Джеоф Уэллс", oppFlag: "🇺🇸", method: "Сдача (гильотина)", event: "CFFC 56", date: "27 фев 2016", round: 1, time: "1:01", location: "Филадельфия, США", note: "" },
            { result: "Поражение", record: "1-2", opponent: "Рикки Бандехас", oppFlag: "🇺🇸", method: "Единогласное решение", event: "CFFC 43", date: "1 ноя 2014", round: 3, time: "5:00", location: "Атлантик-Сити, США", note: "" },
            { result: "Победа", record: "1-1", opponent: "Деннис Думброу", oppFlag: "🇺🇸", method: "TKO (удары)", event: "Ring of Combat 48", date: "24 янв 2014", round: 3, time: "0:50", location: "Атлантик-Сити, США", note: "" },
            { result: "Поражение", record: "0-1", opponent: "Даррен Мима", oppFlag: "🇺🇸", method: "Раздельное решение", event: "Ring of Combat 47", date: "24 янв 2014", round: 3, time: "5:00", location: "Атлантик-Сити, США", note: "Первый бой в профессиональном ММА" }
        ]
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = fighters;
}
''';

with open(r"C:\Users\user\.gemini\antigravity\scratch\ufc-fighters-website\fighters.js", "w", encoding="utf-8") as f:
    f.write(full_fighters_code)

print("COMPLETE ACCURATE fighters.js WRITTEN!")
