const fighters = [

    // =========================================================================
    // HEAVYWEIGHT (ТЯЖЕЛЫЙ ВЕС)
    // =========================================================================
    {
        id: "tom_aspinall",
        name: "Tom Aspinall",
        nickname: "—",
        division: "Heavyweight",
        rank: "C",
        record: "15-3-0",
        sherdog: { ko: 11, sub: 3, dec: 1, lossesKo: 1, lossesSub: 1, lossesDec: 1 },
        ufcStats: { slpm: 7.72, strAcc: 66, sapm: 2.77, strDef: 65, tdAvg: 2.30, tdAcc: 100, tdDef: 100 },
        verdictRating: 985,
        nationality: "UK", flag: "🇬🇧",
        height: "6'5\" (196 cm)", reach: "78.0\" (198 cm)", stance: "Orthodox", age: 33,
        stats: { striking: 95, wrestling: 91, grappling: 93, cardio: 92, power: 98, defense: 90 },
        bio: "UFC Heavyweight Champion. Unprecedented speed for a heavyweight, explosive combinations and BJJ black belt.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-04/ASPINALL_TOM_L_BELT.png",
        fightHistory: [
            { result: "Победа",  record: "15-3",  opponent: "Сергей Павлович",     oppFlag: "🇷🇺", method: "KO (удары)",              event: "UFC 295",                    date: "11 ноя 2023", round: 1, time: "0:52",  location: "Нью-Йорк, США",     note: "Завоевал временный титул чемпиона UFC в тяжелом весе; Выступление вечера" },
            { result: "Победа",  record: "14-3",  opponent: "Марцин Тыбура",       oppFlag: "🇵🇱", method: "KO (удары)",              event: "UFC Fight Night",            date: "22 июл 2023", round: 1, time: "0:38",  location: "Лондон, Великобритания", note: "Выступление вечера" },
            { result: "Поражение",record:"13-3",  opponent: "Кёртис Блэйдс",      oppFlag: "🇺🇸", method: "TKO (травма колена)",     event: "UFC Fight Night",            date: "23 июл 2022", round: 1, time: "0:55",  location: "Лондон, Великобритания", note: "" },
            { result: "Победа",  record: "13-2",  opponent: "Александр Волков",    oppFlag: "🇷🇺", method: "Сдача (удушение сзади)",  event: "UFC Fight Night",            date: "22 янв 2022", round: 1, time: "4:25",  location: "Лондон, Великобритания", note: "Бонус за лучшее выступление" },
            { result: "Победа",  record: "12-2",  opponent: "Андрей Арловский",    oppFlag: "🇧🇾", method: "TKO (удары)",             event: "UFC Fight Night",            date: "19 сен 2021", round: 1, time: "2:16",  location: "Лас-Вегас, США",     note: "" },
            { result: "Победа",  record: "11-2",  opponent: "Альберт Дурнев",      oppFlag: "🇷🇺", method: "TKO (удары)",             event: "UFC Fight Night",            date: "27 июн 2021", round: 1, time: "1:18",  location: "Лас-Вегас, США",     note: "" },
        ]
    },
    {
        id: "jon_jones",
        name: "Jon Jones",
        nickname: "Bones",
        division: "Heavyweight",
        rank: 1,
        record: "27-1-0 (1 NC)",
        sherdog: { ko: 10, sub: 7, dec: 10, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.30, strAcc: 57, sapm: 2.22, strDef: 64, tdAvg: 1.85, tdAcc: 45, tdDef: 95 },
        verdictRating: 995,
        nationality: "USA", flag: "🇺🇸",
        height: "6'4\" (193 cm)", reach: "84.5\" (215 cm)", stance: "Orthodox", age: 38,
        stats: { striking: 88, wrestling: 97, grappling: 93, cardio: 91, power: 86, defense: 96 },
        bio: "Widely regarded as the greatest MMA fighter of all time. Former long-time Light Heavyweight Champion and Heavyweight Champion.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-03/JONES_JON_L_BELT.png",
        fightHistory: [
            { result: "Победа",  record: "27-1",  opponent: "Стипе Миочич",         oppFlag: "🇺🇸", method: "TKO (удары)",             event: "UFC 309",                    date: "16 ноя 2024", round: 3, time: "4:29",  location: "Нью-Йорк, США",     note: "Защита титула чемпиона UFC в тяжелом весе" },
            { result: "Победа",  record: "26-1",  opponent: "Ciryl Gane",            oppFlag: "🇫🇷", method: "Сдача (удушение сзади)",  event: "UFC 285",                    date: "4 мар 2023",  round: 1, time: "2:04",  location: "Лас-Вегас, США",     note: "Завоевал титул в тяжелом весе; Выступление вечера" },
            { result: "Победа",  record: "25-1",  opponent: "Доминик Рейес",         oppFlag: "🇺🇸", method: "Единогласное решение",    event: "UFC 247",                    date: "8 фев 2020",  round: 5, time: "5:00",  location: "Хьюстон, США",       note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "24-1",  opponent: "Тиаго Сантос",          oppFlag: "🇧🇷", method: "Раздельное решение",      event: "UFC 239",                    date: "6 июл 2019",  round: 5, time: "5:00",  location: "Лас-Вегас, США",     note: "Защита титула" },
            { result: "Победа",  record: "23-1",  opponent: "Энтони Смит",           oppFlag: "🇺🇸", method: "Единогласное решение",    event: "UFC 235",                    date: "2 мар 2019",  round: 5, time: "5:00",  location: "Лас-Вегас, США",     note: "Защита титула" },
            { result: "Победа",  record: "22-1",  opponent: "Александр Густафссон", oppFlag: "🇸🇪", method: "TKO (удары)",             event: "UFC 232",                    date: "29 дек 2018", round: 3, time: "2:22",  location: "Инглвуд, США",       note: "Завоевал титул; Бой вечера" },
            { result: "Победа",  record: "19-1",  opponent: "Daniel Cormier",        oppFlag: "🇺🇸", method: "KO (удар ногой)",         event: "UFC 214",                    date: "29 июл 2017", round: 3, time: "3:01",  location: "Анахайм, США",       note: "Позднее изменено на NC" },
        ]
    },
    {
        id: "ciryl_gane",
        name: "Ciryl Gane",
        nickname: "Bon Gamin",
        division: "Heavyweight",
        rank: 2,
        record: "12-2-0",
        sherdog: { ko: 6, sub: 3, dec: 3, lossesKo: 0, lossesSub: 1, lossesDec: 1 },
        ufcStats: { slpm: 5.06, strAcc: 59, sapm: 2.25, strDef: 62, tdAvg: 0.61, tdAcc: 22, tdDef: 42 },
        verdictRating: 910,
        nationality: "France", flag: "🇫🇷",
        height: "6'4\" (193 cm)", reach: "81.0\" (206 cm)", stance: "Orthodox", age: 35,
        stats: { striking: 94, wrestling: 65, grappling: 68, cardio: 93, power: 85, defense: 88 },
        bio: "Former Interim Heavyweight Champion. Remarkably agile footwork kickboxer with Muay Thai mastery.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-03/GANE_CIRYL_L.png",
        fightHistory: [
            { result: "Победа",  record: "12-2",  opponent: "Сергей Павлович",    oppFlag: "🇷🇺", method: "TKO (удары)",          event: "UFC 298",          date: "17 фев 2024", round: 2, time: "1:07",  location: "Анахайм, США",   note: "Выступление вечера" },
            { result: "Победа",  record: "11-2",  opponent: "Tai Tuivasa",         oppFlag: "🇦🇺", method: "TKO (удары)",          event: "UFC Paris",        date: "3 сен 2022",  round: 3, time: "0:38",  location: "Париж, Франция", note: "Выступление вечера" },
            { result: "Поражение",record: "10-2", opponent: "Джон Джонс",          oppFlag: "🇺🇸", method: "Сдача (удушение)",    event: "UFC 285",          date: "4 мар 2023",  round: 1, time: "2:04",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "10-1", opponent: "Стипе Миочич",        oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC 281",          date: "12 ноя 2022", round: 5, time: "5:00",  location: "Нью-Йорк, США",  note: "" },
            { result: "Победа",  record: "10-0",  opponent: "Дерек Льюис",         oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 265",          date: "7 авг 2021",  round: 3, time: "2:07",  location: "Хьюстон, США",   note: "Завоевал временный титул; Выступление вечера" },
        ]
    },
    {
        id: "sergei_pavlovich",
        name: "Sergei Pavlovich",
        nickname: "—",
        division: "Heavyweight",
        rank: 3,
        record: "18-3-0",
        sherdog: { ko: 15, sub: 0, dec: 3, lossesKo: 2, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 6.30, strAcc: 48, sapm: 4.60, strDef: 54, tdAvg: 0.00, tdAcc: 0, tdDef: 75 },
        verdictRating: 890,
        nationality: "Russia", flag: "🇷🇺",
        height: "6'3\" (191 cm)", reach: "84.0\" (213 cm)", stance: "Southpaw", age: 34,
        stats: { striking: 93, wrestling: 75, grappling: 72, cardio: 80, power: 99, defense: 81 },
        bio: "Ferocious knockout artist with a historic streak of first-round finishes in the UFC.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-10/PAVLOVICH_SERGEI_L_10-21.png",
        fightHistory: [
            { result: "Поражение",record: "17-3", opponent: "Том Аспиналл",        oppFlag: "🇬🇧", method: "KO (удары)",           event: "UFC 295",          date: "11 ноя 2023", round: 1, time: "0:52",  location: "Нью-Йорк, США",  note: "" },
            { result: "Поражение",record: "17-2", opponent: "Сирил Ган",           oppFlag: "🇫🇷", method: "TKO (удары)",          event: "UFC 298",          date: "17 фев 2024", round: 2, time: "1:07",  location: "Анахайм, США",   note: "" },
            { result: "Победа",  record: "17-1",  opponent: "Джейлтон Алмейда",    oppFlag: "🇧🇷", method: "KO (удары)",           event: "UFC 295",          date: "11 ноя 2023", round: 1, time: "3:04",  location: "Нью-Йорк, США",  note: "Нокаут вечера" },
            { result: "Победа",  record: "16-1",  opponent: "Кёртис Блэйдс",       oppFlag: "🇺🇸", method: "KO (удар)",            event: "UFC Fight Night",  date: "20 май 2023",  round: 1, time: "1:55",  location: "Лас-Вегас, США", note: "Нокаут вечера" },
            { result: "Победа",  record: "15-1",  opponent: "Тай Туиваза",          oppFlag: "🇦🇺", method: "KO (удары)",           event: "UFC Fight Night",  date: "6 май 2023",   round: 1, time: "0:51",  location: "Джексонвилл, США",note: "Нокаут вечера" },
        ]
    },
    {
        id: "alexander_volkov",
        name: "Alexander Volkov",
        nickname: "Drago",
        division: "Heavyweight",
        rank: 4,
        record: "38-10-0",
        sherdog: { ko: 24, sub: 4, dec: 10, lossesKo: 2, lossesSub: 3, lossesDec: 5 },
        ufcStats: { slpm: 4.90, strAcc: 57, sapm: 3.00, strDef: 53, tdAvg: 0.52, tdAcc: 70, tdDef: 73 },
        verdictRating: 900,
        nationality: "Russia", flag: "🇷🇺",
        height: "6'7\" (201 cm)", reach: "80.0\" (203 cm)", stance: "Orthodox", age: 37,
        stats: { striking: 91, wrestling: 78, grappling: 80, cardio: 92, power: 87, defense: 88 },
        bio: "Towering heavyweight contender. Technical volume kickboxer with vast international experience.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-03/VOLKOV_ALEXANDER_L.png",
        fightHistory: [
            { result: "Победа",  record: "38-10", opponent: "Алексей Олейник",     oppFlag: "🇷🇺", method: "Единогласное решение",event: "UFC Fight Night",  date: "20 апр 2024", round: 3, time: "5:00",  location: "Вашингтон, США", note: "" },
            { result: "Победа",  record: "37-10", opponent: "Том Аспиналл",         oppFlag: "🇬🇧", method: "Единогласное решение",event: "UFC Fight Night",  date: "22 янв 2022", round: 1, time: "0:15",  location: "Лондон, Великобритания", note: "Бой остановлен ввиду травмы; No contest" },
            { result: "Победа",  record: "36-9",  opponent: "Александр Романов",    oppFlag: "🇲🇩", method: "Единогласное решение",event: "UFC Fight Night",  date: "5 ноя 2022",  round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "" },
        ]
    },
    {
        id: "curtis_blaydes",
        name: "Curtis Blaydes",
        nickname: "Razor",
        division: "Heavyweight",
        rank: 5,
        record: "18-5-0 (1 NC)",
        sherdog: { ko: 13, sub: 0, dec: 5, lossesKo: 5, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 3.56, strAcc: 49, sapm: 1.87, strDef: 60, tdAvg: 5.72, tdAcc: 53, tdDef: 33 },
        verdictRating: 875,
        nationality: "USA", flag: "🇺🇸",
        height: "6'3\" (191 cm)", reach: "80.0\" (203 cm)", stance: "Orthodox", age: 35,
        stats: { striking: 78, wrestling: 96, grappling: 85, cardio: 88, power: 88, defense: 83 },
        bio: "NCAA Division I wrestler holding the record for most takedowns in UFC heavyweight history.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-09/BLAYDES_CURTIS_L.png",
        fightHistory: [
            { result: "Победа",  record: "18-5",  opponent: "Мартин Буда",          oppFlag: "🇦🇷", method: "TKO (удары)",          event: "UFC Fight Night",  date: "22 июн 2024", round: 1, time: "4:18",  location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Поражение",record: "17-5", opponent: "Сергей Павлович",      oppFlag: "🇷🇺", method: "KO (удар)",            event: "UFC Fight Night",  date: "20 май 2023",  round: 1, time: "1:55",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "17-4", opponent: "Том Аспиналл",          oppFlag: "🇬🇧", method: "TKO (травма колена)", event: "UFC Fight Night",  date: "23 июл 2022", round: 1, time: "0:55",  location: "Лондон, Великобритания", note: "" },
        ]
    },

    // =========================================================================
    // LIGHT HEAVYWEIGHT (ПОЛУТЯЖЕЛЫЙ ВЕС)
    // =========================================================================
    {
        id: "alex_pereira",
        name: "Alex Pereira",
        nickname: "Poatan",
        division: "Light Heavyweight",
        rank: "C",
        record: "12-2-0",
        sherdog: { ko: 10, sub: 0, dec: 2, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 5.23, strAcc: 63, sapm: 3.51, strDef: 51, tdAvg: 0.18, tdAcc: 100, tdDef: 70 },
        verdictRating: 980,
        nationality: "Brazil", flag: "🇧🇷",
        height: "6'4\" (193 cm)", reach: "79.0\" (200 cm)", stance: "Orthodox", age: 38,
        stats: { striking: 99, wrestling: 68, grappling: 70, cardio: 88, power: 100, defense: 85 },
        bio: "UFC Light Heavyweight Champion & former Middleweight Champion. Legendary kickboxer with devastating left hook.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-04/PEREIRA_ALEX_L_BELT_04-13-2024.png",
        fightHistory: [
            { result: "Победа",  record: "12-2",  opponent: "Жири Прохазка",        oppFlag: "🇨🇿", method: "KO (удары)",           event: "UFC 303",          date: "29 июн 2024", round: 5, time: "4:46",  location: "Лас-Вегас, США", note: "Защита титула; Нокаут вечера" },
            { result: "Победа",  record: "11-2",  opponent: "Пайфер Баев",          oppFlag: "🇧🇬", method: "KO (удар)",            event: "UFC 300",          date: "13 апр 2024", round: 1, time: "0:27",  location: "Лас-Вегас, США", note: "Нокаут вечера; Выступление вечера" },
            { result: "Победа",  record: "10-2",  opponent: "Жири Прохазка",        oppFlag: "🇨🇿", method: "TKO (удары)",          event: "UFC 295",          date: "11 ноя 2023", round: 2, time: "3:37",  location: "Нью-Йорк, США",  note: "Завоевал титул в полутяжелом весе; Бой вечера" },
            { result: "Победа",  record: "9-2",   opponent: "Джамахал Хилл",        oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC 300",          date: "13 апр 2024", round: 1, time: "0:27",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "7-1",   opponent: "Адесанья (MW)",        oppFlag: "🇳🇿", method: "TKO (удары)",          event: "UFC 281",          date: "12 ноя 2022", round: 5, time: "4:21",  location: "Нью-Йорк, США",  note: "Завоевал титул среднего веса" },
        ]
    },
    {
        id: "magomed_ankalaev",
        name: "Magomed Ankalaev",
        nickname: "—",
        division: "Light Heavyweight",
        rank: 1,
        record: "19-1-1 (1 NC)",
        sherdog: { ko: 10, sub: 0, dec: 9, lossesKo: 0, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 3.64, strAcc: 52, sapm: 2.25, strDef: 64, tdAvg: 1.02, tdAcc: 31, tdDef: 86 },
        verdictRating: 945,
        nationality: "Russia", flag: "🇷🇺",
        height: "6'3\" (191 cm)", reach: "75.0\" (191 cm)", stance: "Orthodox", age: 34,
        stats: { striking: 92, wrestling: 94, grappling: 90, cardio: 93, power: 88, defense: 94 },
        bio: "Master of Sport in Combat Sambo. Methodical counter-striker with elite defensive wrestling.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-03/ANKALAEV_MAGOMED_L.png",
        fightHistory: [
            { result: "Победа",  record: "19-1",  opponent: "Джонни Уокер",         oppFlag: "🇧🇷", method: "TKO (удары)",          event: "UFC 294",          date: "21 окт 2023", round: 3, time: "4:07",  location: "Абу-Даби, ОАЭ",  note: "Выступление вечера" },
            { result: "Победа",  record: "18-1",  opponent: "Энтони Смит",           oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 282",          date: "10 дек 2022", round: 1, time: "3:31",  location: "Лас-Вегас, США", note: "" },
            { result: "Ничья",   record: "17-1",  opponent: "Ян Блахович",           oppFlag: "🇵🇱", method: "Раздельная ничья",    event: "UFC 282",          date: "10 дек 2022", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Бой за временный титул" },
            { result: "Победа",  record: "17-0",  opponent: "Том Рашем",             oppFlag: "🇬🇧", method: "KO (удары)",           event: "UFC Fight Night",  date: "21 май 2022",  round: 2, time: "1:43",  location: "Лас-Вегас, США", note: "" },
        ]
    },
    {
        id: "jiri_prochazka",
        name: "Jiří Procházka",
        nickname: "Denisa",
        division: "Light Heavyweight",
        rank: 2,
        record: "30-5-1",
        sherdog: { ko: 26, sub: 3, dec: 1, lossesKo: 4, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 5.75, strAcc: 55, sapm: 5.43, strDef: 40, tdAvg: 0.68, tdAcc: 100, tdDef: 68 },
        verdictRating: 930,
        nationality: "Czech Republic", flag: "🇨🇿",
        height: "6'3\" (191 cm)", reach: "80.0\" (203 cm)", stance: "Switch", age: 33,
        stats: { striking: 95, wrestling: 75, grappling: 82, cardio: 92, power: 95, defense: 76 },
        bio: "Former Light Heavyweight Champion. Wild, unpredictable Bushido samurai style.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-09/PROCHAZKA_JIRI_L_BELT.png",
        fightHistory: [
            { result: "Поражение",record: "30-5", opponent: "Алекс Перейра",         oppFlag: "🇧🇷", method: "KO (удары)",           event: "UFC 303",          date: "29 июн 2024", round: 5, time: "4:46",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "30-4",  opponent: "Алекс Перейра (реванш)",oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 303",          date: "30 дек 2023", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Отвоевал временный титул" },
            { result: "Поражение",record: "29-4", opponent: "Алекс Перейра",         oppFlag: "🇧🇷", method: "TKO (удары)",          event: "UFC 295",          date: "11 ноя 2023", round: 2, time: "3:37",  location: "Нью-Йорк, США",  note: "" },
            { result: "Победа",  record: "29-3",  opponent: "Алекс Перейра",         oppFlag: "🇧🇷", method: "Сдача (удушение)",    event: "UFC 275",          date: "11 июн 2022", round: 5, time: "4:11",  location: "Сингапур",        note: "Завоевал титул; Бой вечера" },
        ]
    },
    {
        id: "jamahal_hill",
        name: "Jamahal Hill",
        nickname: "Sweet Dreams",
        division: "Light Heavyweight",
        rank: 4,
        record: "12-2-0 (1 NC)",
        sherdog: { ko: 7, sub: 0, dec: 5, lossesKo: 2, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 6.90, strAcc: 54, sapm: 3.60, strDef: 52, tdAvg: 0.00, tdAcc: 0, tdDef: 73 },
        verdictRating: 885,
        nationality: "USA", flag: "🇺🇸",
        height: "6'4\" (193 cm)", reach: "79.0\" (200 cm)", stance: "Southpaw", age: 35,
        stats: { striking: 93, wrestling: 70, grappling: 68, cardio: 87, power: 92, defense: 82 },
        bio: "Former Light Heavyweight Champion with crisp, high-volume southpaw boxing.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-01/HILL_JAMAHAL_L.png",
        fightHistory: [
            { result: "Поражение",record: "12-2", opponent: "Алекс Перейра",         oppFlag: "🇧🇷", method: "KO (удары)",           event: "UFC 300",          date: "13 апр 2024", round: 1, time: "0:27",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "12-1",  opponent: "Гловер Тейшейра",       oppFlag: "🇧🇷", method: "KO (удары)",           event: "UFC 283",          date: "21 янв 2023", round: 2, time: "2:20",  location: "Рио-де-Жанейро",  note: "Завоевал титул; Выступление вечера" },
        ]
    },

    // =========================================================================
    // MIDDLEWEIGHT (СРЕДНИЙ ВЕС)
    // =========================================================================
    {
        id: "dricus_du_plessis",
        name: "Dricus du Plessis",
        nickname: "Stillknocks",
        division: "Middleweight",
        rank: "C",
        record: "22-2-0",
        sherdog: { ko: 9, sub: 10, dec: 3, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 6.49, strAcc: 50, sapm: 3.79, strDef: 53, tdAvg: 3.00, tdAcc: 50, tdDef: 50 },
        verdictRating: 960,
        nationality: "South Africa", flag: "🇿🇦",
        height: "6'1\" (185 cm)", reach: "76.0\" (193 cm)", stance: "Switch", age: 32,
        stats: { striking: 89, wrestling: 91, grappling: 88, cardio: 95, power: 94, defense: 85 },
        bio: "UFC Middleweight Champion. Unorthodox pressure fighter with explosive finishing power.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-01/DU_PLESSIS_DRICUS_L_BELT_01-20-2024.png",
        fightHistory: [
            { result: "Победа",  record: "22-2",  opponent: "Шон Стрикленд",        oppFlag: "🇺🇸", method: "Раздельное решение",  event: "UFC 300",          date: "13 апр 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "21-2",  opponent: "Шон Стрикленд",        oppFlag: "🇺🇸", method: "Раздельное решение",  event: "UFC 297",          date: "20 янв 2024", round: 5, time: "5:00",  location: "Торонто, Канада", note: "Завоевал титул; Бой вечера" },
            { result: "Победа",  record: "20-2",  opponent: "Роберт Уиттакер",      oppFlag: "🇦🇺", method: "Сдача (удушение)",    event: "UFC 290",          date: "8 июл 2023",  round: 4, time: "4:28",  location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Победа",  record: "19-2",  opponent: "Дерек Брансон",        oppFlag: "🇺🇸", method: "Сдача (удушение)",    event: "UFC 282",          date: "10 дек 2022", round: 1, time: "4:21",  location: "Лас-Вегас, США", note: "" },
        ]
    },
    {
        id: "israel_adesanya",
        name: "Israel Adesanya",
        nickname: "The Last Stylebender",
        division: "Middleweight",
        rank: 1,
        record: "24-4-0",
        sherdog: { ko: 16, sub: 0, dec: 8, lossesKo: 1, lossesSub: 1, lossesDec: 2 },
        ufcStats: { slpm: 3.93, strAcc: 48, sapm: 3.11, strDef: 56, tdAvg: 0.06, tdAcc: 14, tdDef: 77 },
        verdictRating: 940,
        nationality: "New Zealand", flag: "🇳🇿",
        height: "6'4\" (193 cm)", reach: "80.0\" (203 cm)", stance: "Switch", age: 37,
        stats: { striking: 98, wrestling: 72, grappling: 70, cardio: 93, power: 88, defense: 92 },
        bio: "Two-time UFC Middleweight Champion. World-class kickboxer renowned for technical counter-striking.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-09/ADESANYA_ISRAEL_L.png",
        fightHistory: [
            { result: "Поражение",record: "24-4", opponent: "Дрикус дю Плесси",     oppFlag: "🇿🇦", method: "Раздельное решение",  event: "UFC 305",          date: "17 авг 2024", round: 5, time: "5:00",  location: "Перт, Австралия", note: "" },
            { result: "Победа",  record: "24-3",  opponent: "Шон Стрикленд",         oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC 293",          date: "9 сен 2023",  round: 5, time: "5:00",  location: "Сидней, Австралия",note: "Бой вечера" },
            { result: "Поражение",record: "23-3", opponent: "Алекс Перейра",          oppFlag: "🇧🇷", method: "TKO (удары)",          event: "UFC 281",          date: "12 ноя 2022", round: 5, time: "4:21",  location: "Нью-Йорк, США",  note: "Потерял титул" },
            { result: "Победа",  record: "23-2",  opponent: "Роберт Уиттакер",        oppFlag: "🇦🇺", method: "Единогласное решение",event: "UFC 271",          date: "12 фев 2022", round: 5, time: "5:00",  location: "Хьюстон, США",   note: "Защита титула" },
        ]
    },
    {
        id: "robert_whittaker",
        name: "Robert Whittaker",
        nickname: "The Reaper",
        division: "Middleweight",
        rank: 2,
        record: "26-8-0",
        sherdog: { ko: 10, sub: 5, dec: 11, lossesKo: 3, lossesSub: 2, lossesDec: 3 },
        ufcStats: { slpm: 4.47, strAcc: 42, sapm: 3.37, strDef: 60, tdAvg: 0.80, tdAcc: 37, tdDef: 82 },
        verdictRating: 920,
        nationality: "Australia", flag: "🇦🇺",
        height: "6'0\" (183 cm)", reach: "73.5\" (187 cm)", stance: "Orthodox", age: 35,
        stats: { striking: 94, wrestling: 90, grappling: 84, cardio: 92, power: 87, defense: 91 },
        bio: "Former Middleweight Champion. Blitz karate technician with legendary anti-wrestling defense.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-02/WHITTAKER_ROBERT_L.png",
        fightHistory: [
            { result: "Победа",  record: "26-8",  opponent: "Шон Стрикленд",        oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC Fight Night",  date: "22 июн 2024", round: 5, time: "5:00",  location: "Крайстчёрч, НЗ",  note: "Бой вечера" },
            { result: "Поражение",record: "25-8", opponent: "Дрикус дю Плесси",     oppFlag: "🇿🇦", method: "Сдача (удушение)",    event: "UFC 290",          date: "8 июл 2023",  round: 4, time: "4:28",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "25-7",  opponent: "Пауло Коста",           oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 284",          date: "12 фев 2023", round: 5, time: "5:00",  location: "Перт, Австралия", note: "Бой вечера" },
        ]
    },
    {
        id: "khamzat_chimaev",
        name: "Khamzat Chimaev",
        nickname: "Borz",
        division: "Middleweight",
        rank: 3,
        record: "14-0-0",
        sherdog: { ko: 6, sub: 6, dec: 2, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 5.72, strAcc: 58, sapm: 3.46, strDef: 42, tdAvg: 3.99, tdAcc: 46, tdDef: 100 },
        verdictRating: 965,
        nationality: "UAE / Russia", flag: "🇦🇪",
        height: "6'2\" (188 cm)", reach: "75.0\" (190 cm)", stance: "Orthodox", age: 32,
        stats: { striking: 82, wrestling: 99, grappling: 95, cardio: 84, power: 94, defense: 88 },
        bio: "Undefeated phenom known for extreme aggression, ragdoll wrestling, and fast finishes.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-10/CHIMAEV_KHAMZAT_L_10-21.png",
        fightHistory: [
            { result: "Победа",  record: "14-0",  opponent: "Роберт Уиттакер",      oppFlag: "🇦🇺", method: "Единогласное решение",event: "UFC 308",          date: "26 окт 2024", round: 5, time: "5:00",  location: "Абу-Даби, ОАЭ",  note: "Бой вечера" },
            { result: "Победа",  record: "13-0",  opponent: "Камару Усман",          oppFlag: "🇳🇬", method: "Единогласное решение",event: "UFC 294",          date: "21 окт 2023", round: 5, time: "5:00",  location: "Абу-Даби, ОАЭ",  note: "Бой вечера" },
            { result: "Победа",  record: "12-0",  opponent: "Гилберт Бернс",         oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 273",          date: "9 апр 2022",  round: 3, time: "5:00",  location: "Джексонвилл, США",note: "Бой вечера" },
        ]
    },
    {
        id: "sean_strickland",
        name: "Sean Strickland",
        nickname: "Tarzan",
        division: "Middleweight",
        rank: 4,
        record: "29-6-0",
        sherdog: { ko: 11, sub: 4, dec: 14, lossesKo: 2, lossesSub: 0, lossesDec: 4 },
        ufcStats: { slpm: 5.89, strAcc: 41, sapm: 4.20, strDef: 65, tdAvg: 0.85, tdAcc: 64, tdDef: 84 },
        verdictRating: 935,
        nationality: "USA", flag: "🇺🇸",
        height: "6'1\" (185 cm)", reach: "76.0\" (193 cm)", stance: "Orthodox", age: 35,
        stats: { striking: 93, wrestling: 84, grappling: 80, cardio: 97, power: 82, defense: 96 },
        bio: "Former Middleweight Champion. Defensive boxing master with non-stop forward pressure.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-01/STRICKLAND_SEAN_L_BELT.png",
        fightHistory: [
            { result: "Поражение",record: "29-6", opponent: "Дрикус дю Плесси",     oppFlag: "🇿🇦", method: "Раздельное решение",  event: "UFC 300",          date: "13 апр 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "29-5", opponent: "Дрикус дю Плесси",     oppFlag: "🇿🇦", method: "Раздельное решение",  event: "UFC 297",          date: "20 янв 2024", round: 5, time: "5:00",  location: "Торонто, Канада", note: "Потерял титул" },
            { result: "Победа",  record: "29-4",  opponent: "Исраэль Адесанья",       oppFlag: "🇳🇿", method: "Единогласное решение",event: "UFC 293",          date: "9 сен 2023",  round: 5, time: "5:00",  location: "Сидней, Австралия",note: "Завоевал титул; Нокаут вечера" },
        ]
    },

    // =========================================================================
    // WELTERWEIGHT (ПОЛУСРЕДНИЙ ВЕС)
    // =========================================================================
    {
        id: "belal_muhammad",
        name: "Belal Muhammad",
        nickname: "Remember the Name",
        division: "Welterweight",
        rank: "C",
        record: "24-3-0 (1 NC)",
        sherdog: { ko: 5, sub: 1, dec: 18, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 4.29, strAcc: 43, sapm: 3.64, strDef: 57, tdAvg: 2.47, tdAcc: 35, tdDef: 92 },
        verdictRating: 940,
        nationality: "USA / Palestine", flag: "🇵🇸",
        height: "5'11\" (180 cm)", reach: "72.0\" (183 cm)", stance: "Orthodox", age: 38,
        stats: { striking: 87, wrestling: 96, grappling: 90, cardio: 99, power: 80, defense: 94 },
        bio: "UFC Welterweight Champion. High-tempo pressure wrestler with boundless conditioning.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-07/MUHAMMAD_BELAL_L_BELT_07-27-2024.png",
        fightHistory: [
            { result: "Победа",  record: "24-3",  opponent: "Леон Эдвардс",          oppFlag: "🇬🇧", method: "Единогласное решение",event: "UFC 304",          date: "27 июл 2024", round: 5, time: "5:00",  location: "Манчестер, Великобритания", note: "Завоевал титул; Бой вечера" },
            { result: "Победа",  record: "23-3",  opponent: "Гилберт Бернс",         oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 288",          date: "6 май 2023",   round: 5, time: "5:00",  location: "Ньюарк, США",    note: "" },
            { result: "Победа",  record: "22-3",  opponent: "Шавкат Рахмонов",       oppFlag: "🇰🇿", method: "Единогласное решение",event: "UFC 310",          date: "7 дек 2024",  round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Защита титула; Бой вечера" },
        ]
    },
    {
        id: "shavkat_rakhmonov",
        name: "Shavkat Rakhmonov",
        nickname: "Nomad",
        division: "Welterweight",
        rank: 1,
        record: "18-0-0",
        sherdog: { ko: 8, sub: 10, dec: 0, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.38, strAcc: 56, sapm: 2.61, strDef: 54, tdAvg: 1.49, tdAcc: 57, tdDef: 100 },
        verdictRating: 975,
        nationality: "Kazakhstan", flag: "🇰🇿",
        height: "6'1\" (185 cm)", reach: "77.0\" (196 cm)", stance: "Orthodox", age: 31,
        stats: { striking: 93, wrestling: 95, grappling: 97, cardio: 92, power: 91, defense: 89 },
        bio: "Undefeated 100% finish rate fighter. Master of Sports in Sambo with Muay Thai knees.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-10/RAKHMONOV_SHAVKAT_L_10-21.png",
        fightHistory: [
            { result: "Победа",  record: "18-0",  opponent: "Белал Мухаммад",        oppFlag: "🇵🇸", method: "Единогласное решение",event: "UFC 310",          date: "7 дек 2024",  round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Победа",  record: "17-0",  opponent: "Стивен Томпсон",        oppFlag: "🇺🇸", method: "Сдача (удушение)",    event: "UFC 296",          date: "16 дек 2023", round: 2, time: "4:54",  location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа",  record: "16-0",  opponent: "Нейт Диаз",              oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 288",          date: "6 май 2023",   round: 2, time: "3:49",  location: "Ньюарк, США",    note: "Выступление вечера" },
        ]
    },
    {
        id: "leon_edwards",
        name: "Leon Edwards",
        nickname: "Rocky",
        division: "Welterweight",
        rank: 2,
        record: "22-4-0 (1 NC)",
        sherdog: { ko: 7, sub: 3, dec: 12, lossesKo: 0, lossesSub: 0, lossesDec: 4 },
        ufcStats: { slpm: 2.75, strAcc: 53, sapm: 2.40, strDef: 54, tdAvg: 1.25, tdAcc: 34, tdDef: 68 },
        verdictRating: 920,
        nationality: "UK", flag: "🇬🇧",
        height: "6'2\" (188 cm)", reach: "74.0\" (188 cm)", stance: "Southpaw", age: 34,
        stats: { striking: 93, wrestling: 82, grappling: 83, cardio: 90, power: 82, defense: 92 },
        bio: "Former Welterweight Champion. Smooth southpaw striker famous for historic head-kick KO.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-07/EDWARDS_LEON_L_BELT.png",
        fightHistory: [
            { result: "Поражение",record: "22-4", opponent: "Белал Мухаммад",        oppFlag: "🇵🇸", method: "Единогласное решение",event: "UFC 304",          date: "27 июл 2024", round: 5, time: "5:00",  location: "Манчестер, Великобритания", note: "" },
            { result: "Победа",  record: "22-3",  opponent: "Камару Усман III",       oppFlag: "🇳🇬", method: "Единогласное решение",event: "UFC 286",          date: "18 мар 2023", round: 5, time: "5:00",  location: "Лондон, Великобритания", note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "21-3",  opponent: "Камару Усман II",        oppFlag: "🇳🇬", method: "KO (удар ногой)",      event: "UFC 278",          date: "20 авг 2022", round: 5, time: "4:04",  location: "Солт-Лейк-Сити, США", note: "Завоевал титул; Нокаут/Бой вечера" },
        ]
    },
    {
        id: "kamaru_usman",
        name: "Kamaru Usman",
        nickname: "The Nigerian Nightmare",
        division: "Welterweight",
        rank: 3,
        record: "20-4-0",
        sherdog: { ko: 9, sub: 1, dec: 10, lossesKo: 1, lossesSub: 1, lossesDec: 2 },
        ufcStats: { slpm: 4.57, strAcc: 52, sapm: 2.75, strDef: 56, tdAvg: 2.82, tdAcc: 48, tdDef: 97 },
        verdictRating: 930,
        nationality: "Nigeria / USA", flag: "🇳🇬",
        height: "6'0\" (183 cm)", reach: "76.0\" (193 cm)", stance: "Orthodox", age: 39,
        stats: { striking: 88, wrestling: 97, grappling: 91, cardio: 94, power: 89, defense: 93 },
        bio: "Former long-reigning Welterweight Champion. NCAA Division II wrestling champion.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-10/USMAN_KAMARU_L.png",
        fightHistory: [
            { result: "Поражение",record: "20-4", opponent: "Хамзат Чимаев",         oppFlag: "🇦🇪", method: "Единогласное решение",event: "UFC 294",          date: "21 окт 2023", round: 5, time: "5:00",  location: "Абу-Даби, ОАЭ",  note: "" },
            { result: "Поражение",record: "20-3", opponent: "Леон Эдвардс",           oppFlag: "🇬🇧", method: "Единогласное решение",event: "UFC 286",          date: "18 мар 2023", round: 5, time: "5:00",  location: "Лондон, Великобритания", note: "" },
            { result: "Поражение",record: "20-2", opponent: "Леон Эдвардс",           oppFlag: "🇬🇧", method: "KO (удар ногой)",      event: "UFC 278",          date: "20 авг 2022", round: 5, time: "4:04",  location: "Солт-Лейк-Сити, США", note: "Потерял титул" },
        ]
    },
    {
        id: "jack_della_maddalena",
        name: "Jack Della Maddalena",
        nickname: "The Gunslinger",
        division: "Welterweight",
        rank: 4,
        record: "17-2-0",
        sherdog: { ko: 12, sub: 2, dec: 3, lossesKo: 1, lossesSub: 1, lossesDec: 0 },
        ufcStats: { slpm: 7.20, strAcc: 53, sapm: 4.80, strDef: 67, tdAvg: 0.20, tdAcc: 20, tdDef: 82 },
        verdictRating: 915,
        nationality: "Australia", flag: "🇦🇺",
        height: "5'11\" (180 cm)", reach: "73.0\" (185 cm)", stance: "Switch", age: 29,
        stats: { striking: 95, wrestling: 75, grappling: 80, cardio: 91, power: 90, defense: 87 },
        bio: "Australian boxing prodigy with devastating body-head combination punching.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-12/DELLA_MADDALENA_JACK_L_12-16.png",
        fightHistory: [
            { result: "Победа",  record: "17-2",  opponent: "Джефф Нил",             oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC 312",          date: "9 фев 2025",  round: 2, time: "2:49",  location: "Сидней, Австралия",note: "Нокаут вечера" },
            { result: "Победа",  record: "16-2",  opponent: "Кевин Холланд",          oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC 299",          date: "9 мар 2024",  round: 1, time: "1:52",  location: "Майами, США",     note: "Нокаут вечера" },
        ]
    },

    // =========================================================================
    // LIGHTWEIGHT (ЛЕГКИЙ ВЕС)
    // =========================================================================
    {
        id: "islam_makhachev",
        name: "Islam Makhachev",
        nickname: "—",
        division: "Lightweight",
        rank: "C",
        record: "26-1-0",
        sherdog: { ko: 5, sub: 12, dec: 9, lossesKo: 1, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 3.17, strAcc: 60, sapm: 1.24, strDef: 61, tdAvg: 3.17, tdAcc: 60, tdDef: 90 },
        verdictRating: 990,
        nationality: "Russia", flag: "🇷🇺",
        height: "5'10\" (178 cm)", reach: "70.5\" (179 cm)", stance: "Southpaw", age: 34,
        stats: { striking: 86, wrestling: 98, grappling: 97, cardio: 95, power: 82, defense: 94 },
        bio: "UFC Lightweight Champion & P4P #1. World Combat Sambo Champion tutored by Khabib.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-02/MAKHACHEV_ISLAM_L_BELT_02-17-2024.png",
        fightHistory: [
            { result: "Победа",  record: "26-1",  opponent: "Дастин Пуарье",         oppFlag: "🇺🇸", method: "Сдача (удушение)",    event: "UFC 302",          date: "1 июн 2024",  round: 5, time: "1:06",  location: "Ньюарк, США",    note: "Защита титула; Выступление вечера" },
            { result: "Победа",  record: "25-1",  opponent: "Александр Волкановски", oppFlag: "🇦🇺", method: "Единогласное решение",event: "UFC 298",          date: "17 фев 2024", round: 5, time: "5:00",  location: "Анахайм, США",   note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "24-1",  opponent: "Александр Волкановски", oppFlag: "🇦🇺", method: "KO (удар)",            event: "UFC 294",          date: "21 окт 2023", round: 1, time: "2:06",  location: "Абу-Даби, ОАЭ",  note: "Защита титула; Нокаут вечера" },
            { result: "Победа",  record: "23-1",  opponent: "Чарльз Оливейра",       oppFlag: "🇧🇷", method: "Сдача (кимура)",      event: "UFC 280",          date: "22 окт 2022", round: 2, time: "3:16",  location: "Абу-Даби, ОАЭ",  note: "Завоевал титул; Выступление вечера" },
        ]
    },
    {
        id: "arman_tsarukyan",
        name: "Arman Tsarukyan",
        nickname: "Ahalkalakets",
        division: "Lightweight",
        rank: 1,
        record: "22-3-0",
        sherdog: { ko: 9, sub: 5, dec: 8, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 3.88, strAcc: 48, sapm: 2.68, strDef: 54, tdAvg: 3.40, tdAcc: 36, tdDef: 75 },
        verdictRating: 955,
        nationality: "Armenia / Russia", flag: "🇦🇲",
        height: "5'7\" (170 cm)", reach: "72.0\" (183 cm)", stance: "Orthodox", age: 29,
        stats: { striking: 90, wrestling: 96, grappling: 92, cardio: 94, power: 88, defense: 90 },
        bio: "#1 Lightweight contender. Explosive wrestler with heavy head kicks and relentless ground control.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-06/TSARUKYAN_ARMAN_L_06-22-2024.png",
        fightHistory: [
            { result: "Победа",  record: "22-3",  opponent: "Чарльз Оливейра",       oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 300",          date: "13 апр 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Победа",  record: "21-3",  opponent: "Гарри Кинан",           oppFlag: "🇮🇪", method: "KO (удары)",           event: "UFC Fight Night",  date: "22 июн 2024", round: 1, time: "1:48",  location: "Лас-Вегас, США", note: "Нокаут вечера" },
            { result: "Победа",  record: "20-3",  opponent: "Ислам Мадалиев",        oppFlag: "🇺🇿", method: "Единогласное решение",event: "UFC 300",          date: "16 мар 2024", round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "" },
        ]
    },
    {
        id: "charles_oliveira",
        name: "Charles Oliveira",
        nickname: "Do Bronx",
        division: "Lightweight",
        rank: 2,
        record: "34-10-0 (1 NC)",
        sherdog: { ko: 10, sub: 21, dec: 3, lossesKo: 4, lossesSub: 4, lossesDec: 2 },
        ufcStats: { slpm: 3.54, strAcc: 54, sapm: 3.19, strDef: 51, tdAvg: 2.30, tdAcc: 40, tdDef: 55 },
        verdictRating: 945,
        nationality: "Brazil", flag: "🇧🇷",
        height: "5'10\" (178 cm)", reach: "74.0\" (188 cm)", stance: "Orthodox", age: 36,
        stats: { striking: 93, wrestling: 80, grappling: 100, cardio: 88, power: 90, defense: 80 },
        bio: "Former Lightweight Champion. UFC all-time record for most submission victories (21).",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-10/OLIVEIRA_CHARLES_L.png",
        fightHistory: [
            { result: "Поражение",record: "34-10",opponent: "Арман Царукян",         oppFlag: "🇦🇲", method: "Единогласное решение",event: "UFC 300",          date: "13 апр 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "34-9", opponent: "Ислам Махачев",          oppFlag: "🇷🇺", method: "Сдача (кимура)",      event: "UFC 280",          date: "22 окт 2022", round: 2, time: "3:16",  location: "Абу-Даби, ОАЭ",  note: "Потерял титул" },
            { result: "Победа",  record: "34-8",  opponent: "Джастин Гэтжи",          oppFlag: "🇺🇸", method: "Сдача (удушение)",    event: "UFC 274",          date: "7 май 2022",   round: 1, time: "3:22",  location: "Финикс, США",    note: "Защита титула; Бой вечера" },
        ]
    },
    {
        id: "justin_gaethje",
        name: "Justin Gaethje",
        nickname: "The Highlight",
        division: "Lightweight",
        rank: 3,
        record: "25-5-0",
        sherdog: { ko: 20, sub: 1, dec: 4, lossesKo: 3, lossesSub: 2, lossesDec: 0 },
        ufcStats: { slpm: 7.35, strAcc: 60, sapm: 7.50, strDef: 53, tdAvg: 0.13, tdAcc: 25, tdDef: 75 },
        verdictRating: 935,
        nationality: "USA", flag: "🇺🇸",
        height: "5'11\" (180 cm)", reach: "70.0\" (178 cm)", stance: "Orthodox", age: 37,
        stats: { striking: 95, wrestling: 85, grappling: 68, cardio: 90, power: 96, defense: 83 },
        bio: "Former BMF & Interim Lightweight Champion. Destructive leg chopper with unmatched violence.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-04/GAETHJE_JUSTIN_L.png",
        fightHistory: [
            { result: "Поражение",record: "25-5", opponent: "Ислам Махачев",          oppFlag: "🇷🇺", method: "Сдача (удушение)",    event: "UFC 302",          date: "1 июн 2024",  round: 5, time: "1:06",  location: "Ньюарк, США",    note: "" },
            { result: "Победа",  record: "25-4",  opponent: "Дастин Пуарье",           oppFlag: "🇺🇸", method: "KO (удар ногой)",      event: "UFC 291",          date: "29 июл 2023", round: 2, time: "3:22",  location: "Солт-Лейк-Сити, США",note: "Бой/Нокаут вечера; BMF пояс" },
            { result: "Поражение",record: "24-4", opponent: "Чарльз Оливейра",        oppFlag: "🇧🇷", method: "Сдача (удушение)",    event: "UFC 274",          date: "7 май 2022",   round: 1, time: "3:22",  location: "Финикс, США",    note: "" },
        ]
    },
    {
        id: "dustin_poirier",
        name: "Dustin Poirier",
        nickname: "The Diamond",
        division: "Lightweight",
        rank: 4,
        record: "30-9-0 (1 NC)",
        sherdog: { ko: 15, sub: 8, dec: 7, lossesKo: 3, lossesSub: 3, lossesDec: 3 },
        ufcStats: { slpm: 5.45, strAcc: 50, sapm: 4.29, strDef: 54, tdAvg: 1.34, tdAcc: 36, tdDef: 63 },
        verdictRating: 930,
        nationality: "USA", flag: "🇺🇸",
        height: "5'9\" (175 cm)", reach: "72.0\" (183 cm)", stance: "Southpaw", age: 37,
        stats: { striking: 96, wrestling: 78, grappling: 82, cardio: 93, power: 90, defense: 87 },
        bio: "Former Interim Lightweight Champion with elite southpaw boxing and guillotine threat.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2021-10/POIRIER_DUSTIN_L.png",
        fightHistory: [
            { result: "Поражение",record: "30-9", opponent: "Ислам Махачев",          oppFlag: "🇷🇺", method: "Сдача (удушение)",    event: "UFC 302",          date: "1 июн 2024",  round: 5, time: "1:06",  location: "Ньюарк, США",    note: "" },
            { result: "Поражение",record: "30-8", opponent: "Джастин Гэтжи",          oppFlag: "🇺🇸", method: "KO (удар ногой)",      event: "UFC 291",          date: "29 июл 2023", round: 2, time: "3:22",  location: "Солт-Лейк-Сити, США",note: "" },
            { result: "Победа",  record: "30-7",  opponent: "Конор МакГрегор III",    oppFlag: "🇮🇪", method: "TKO (удары)",          event: "UFC 264",          date: "10 июл 2021", round: 1, time: "5:00",  location: "Лас-Вегас, США", note: "Победа по техническому нокауту; Бой вечера" },
        ]
    },
    {
        id: "conor_mcgregor",
        name: "Conor McGregor",
        nickname: "The Notorious",
        division: "Lightweight",
        rank: 5,
        record: "22-6-0",
        sherdog: { ko: 19, sub: 1, dec: 2, lossesKo: 3, lossesSub: 2, lossesDec: 1 },
        ufcStats: { slpm: 5.24, strAcc: 49, sapm: 4.06, strDef: 53, tdAvg: 0.61, tdAcc: 57, tdDef: 76 },
        verdictRating: 895,
        nationality: "Ireland", flag: "🇮🇪",
        height: "5'9\" (175 cm)", reach: "74.0\" (188 cm)", stance: "Southpaw", age: 37,
        stats: { striking: 94, wrestling: 65, grappling: 68, cardio: 75, power: 90, defense: 80 },
        bio: "First simultaneous two-division champion in UFC history. Biggest PPV draw in MMA history.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2021-06/MCGREGOR_CONOR_L.png",
        fightHistory: [
            { result: "Поражение",record: "22-6", opponent: "Дастин Пуарье",           oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 264",          date: "10 июл 2021", round: 1, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "22-5", opponent: "Дастин Пуарье",           oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 257",          date: "23 янв 2021", round: 2, time: "2:32",  location: "Абу-Даби, ОАЭ",  note: "" },
            { result: "Победа",  record: "22-4",  opponent: "Дональд Серроне",          oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 246",          date: "18 янв 2020", round: 1, time: "0:40",  location: "Лас-Вегас, США", note: "Нокаут вечера" },
            { result: "Поражение",record: "21-4", opponent: "Хабиб Нурмагомедов",      oppFlag: "🇷🇺", method: "Сдача (удушение)",    event: "UFC 229",          date: "6 окт 2018",  round: 4, time: "3:03",  location: "Лас-Вегас, США", note: "Бой за титул легкого веса" },
            { result: "Победа",  record: "21-3",  opponent: "Эдди Альварес",            oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 205",          date: "12 ноя 2016", round: 2, time: "3:04",  location: "Нью-Йорк, США",  note: "Завоевал титул легкого веса; Первый двойной чемпион UFC" },
            { result: "Победа",  record: "19-3",  opponent: "Нэйт Диаз II",             oppFlag: "🇺🇸", method: "Решение большинства", event: "UFC 202",          date: "20 авг 2016", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Бой вечера" },
            { result: "Победа",  record: "18-3",  opponent: "Жозе Альдо",               oppFlag: "🇧🇷", method: "KO (удар)",            event: "UFC 194",          date: "12 дек 2015", round: 1, time: "0:13",  location: "Лас-Вегас, США", note: "Завоевал титул полулегкого веса; Рекорд UFC" },
        ]
    },
    {
        id: "khabib_nurmagomedov",
        name: "Khabib Nurmagomedov",
        nickname: "The Eagle",
        division: "Lightweight",
        rank: 6,
        record: "29-0-0",
        sherdog: { ko: 8, sub: 11, dec: 10, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.10, strAcc: 48, sapm: 1.60, strDef: 60, tdAvg: 5.32, tdAcc: 47, tdDef: 82 },
        verdictRating: 1000,
        nationality: "Russia", flag: "🇷🇺",
        height: "5'10\" (178 cm)", reach: "70.0\" (178 cm)", stance: "Orthodox", age: 37,
        stats: { striking: 78, wrestling: 100, grappling: 99, cardio: 98, power: 78, defense: 94 },
        bio: "UFC Hall of Famer & undefeated Lightweight Champion (29-0). Unmatched wrestling dominance.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2021-05/NURMAGOMEDOV_KHABIB_L.png",
        fightHistory: [
            { result: "Победа",  record: "29-0",  opponent: "Джастин Гэтжи",          oppFlag: "🇺🇸", method: "Сдача (треугольник)", event: "UFC 254",          date: "24 окт 2020", round: 2, time: "1:34",  location: "Абу-Даби, ОАЭ",  note: "Защита титула; Объявил о завершении карьеры" },
            { result: "Победа",  record: "28-0",  opponent: "Конор МакГрегор",          oppFlag: "🇮🇪", method: "Сдача (удушение)",    event: "UFC 229",          date: "6 окт 2018",  round: 4, time: "3:03",  location: "Лас-Вегас, США", note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "27-0",  opponent: "Аль Яквинта",              oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC 223",          date: "7 апр 2018",  round: 5, time: "5:00",  location: "Нью-Йорк, США",  note: "Завоевал вакантный титул" },
        ]
    },

    // =========================================================================
    // FEATHERWEIGHT (ПОЛУЛЕГКИЙ ВЕС)
    // =========================================================================
    {
        id: "ilia_topuria",
        name: "Ilia Topuria",
        nickname: "El Matador",
        division: "Featherweight",
        rank: "C",
        record: "16-0-0",
        sherdog: { ko: 6, sub: 8, dec: 2, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.40, strAcc: 46, sapm: 3.35, strDef: 65, tdAvg: 1.92, tdAcc: 56, tdDef: 92 },
        verdictRating: 985,
        nationality: "Spain / Georgia", flag: "🇪🇸",
        height: "5'7\" (170 cm)", reach: "69.0\" (175 cm)", stance: "Orthodox", age: 29,
        stats: { striking: 96, wrestling: 89, grappling: 91, cardio: 91, power: 94, defense: 91 },
        bio: "Undefeated UFC Featherweight Champion. Devastating boxing combined with Greco-Roman grappling.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-02/TOPURIA_ILIA_L_BELT_02-17-2024.png",
        fightHistory: [
            { result: "Победа",  record: "16-0",  opponent: "Макс Холлоуэй",          oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC 308",          date: "26 окт 2024", round: 3, time: "2:30",  location: "Абу-Даби, ОАЭ",  note: "Защита титула; Нокаут вечера" },
            { result: "Победа",  record: "15-0",  opponent: "Александр Волкановски",  oppFlag: "🇦🇺", method: "KO (удары)",           event: "UFC 298",          date: "17 фев 2024", round: 2, time: "3:06",  location: "Анахайм, США",   note: "Завоевал титул; Нокаут/Выступление вечера" },
            { result: "Победа",  record: "14-0",  opponent: "Джош Эмет",               oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC Fight Night",  date: "20 май 2023",  round: 2, time: "1:38",  location: "Лас-Вегас, США", note: "Нокаут вечера" },
        ]
    },
    {
        id: "alexander_volkanovski",
        name: "Alexander Volkanovski",
        nickname: "The Great",
        division: "Featherweight",
        rank: 1,
        record: "26-4-0",
        sherdog: { ko: 13, sub: 3, dec: 10, lossesKo: 3, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 6.19, strAcc: 50, sapm: 3.40, strDef: 58, tdAvg: 1.84, tdAcc: 37, tdDef: 70 },
        verdictRating: 950,
        nationality: "Australia", flag: "🇦🇺",
        height: "5'6\" (168 cm)", reach: "71.0\" (180 cm)", stance: "Orthodox", age: 37,
        stats: { striking: 95, wrestling: 90, grappling: 85, cardio: 98, power: 84, defense: 93 },
        bio: "Former long-reigning Featherweight Champion with masterful feints and relentless volume.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-03/VOLKANOVSKI_ALEXANDER_L.png",
        fightHistory: [
            { result: "Поражение",record: "26-4", opponent: "Илия Топурия",           oppFlag: "🇪🇸", method: "KO (удары)",           event: "UFC 308",          date: "26 окт 2024", round: 3, time: "2:30",  location: "Абу-Даби, ОАЭ",  note: "" },
            { result: "Поражение",record: "26-3", opponent: "Илия Топурия",           oppFlag: "🇪🇸", method: "KO (удары)",           event: "UFC 298",          date: "17 фев 2024", round: 2, time: "3:06",  location: "Анахайм, США",   note: "Потерял титул" },
            { result: "Победа",  record: "26-2",  opponent: "Юрайя Фабер",            oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC 290",          date: "8 июл 2023",  round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Защита титула" },
        ]
    },
    {
        id: "max_holloway",
        name: "Max Holloway",
        nickname: "Blessed",
        division: "Featherweight",
        rank: 2,
        record: "26-8-0",
        sherdog: { ko: 12, sub: 2, dec: 12, lossesKo: 1, lossesSub: 1, lossesDec: 6 },
        ufcStats: { slpm: 7.17, strAcc: 47, sapm: 4.72, strDef: 59, tdAvg: 0.27, tdAcc: 53, tdDef: 84 },
        verdictRating: 960,
        nationality: "USA", flag: "🇺🇸",
        height: "5'11\" (180 cm)", reach: "69.0\" (175 cm)", stance: "Orthodox", age: 34,
        stats: { striking: 97, wrestling: 72, grappling: 74, cardio: 100, power: 82, defense: 91 },
        bio: "BMF & former Featherweight Champion. UFC all-time record for most strikes landed.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-04/HOLLOWAY_MAX_L_04-13-2024.png",
        fightHistory: [
            { result: "Поражение",record: "26-8", opponent: "Илия Топурия",           oppFlag: "🇪🇸", method: "KO (удары)",           event: "UFC 308",          date: "26 окт 2024", round: 3, time: "2:30",  location: "Абу-Даби, ОАЭ",  note: "" },
            { result: "Победа",  record: "26-7",  opponent: "Джастин Гэтжи",           oppFlag: "🇺🇸", method: "KO (удар)",            event: "UFC 300",          date: "13 апр 2024", round: 5, time: "4:46",  location: "Лас-Вегас, США", note: "Нокаут/Бой вечера; Легендарный бой" },
            { result: "Победа",  record: "25-7",  opponent: "Майкл Чандлер",           oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC Fight Night",  date: "14 янв 2023", round: 5, time: "5:00",  location: "Абу-Даби, ОАЭ",  note: "BMF пояс" },
        ]
    },
    {
        id: "diego_lopes",
        name: "Diego Lopes",
        nickname: "—",
        division: "Featherweight",
        rank: 3,
        record: "26-6-0",
        sherdog: { ko: 10, sub: 12, dec: 4, lossesKo: 2, lossesSub: 0, lossesDec: 4 },
        ufcStats: { slpm: 3.22, strAcc: 52, sapm: 4.10, strDef: 41, tdAvg: 0.80, tdAcc: 33, tdDef: 46 },
        verdictRating: 915,
        nationality: "Brazil", flag: "🇧🇷",
        height: "5'11\" (180 cm)", reach: "72.5\" (184 cm)", stance: "Orthodox", age: 31,
        stats: { striking: 91, wrestling: 80, grappling: 96, cardio: 89, power: 90, defense: 84 },
        bio: "Aggressive crowd-pleaser combining wild punch power with elite BJJ submissions.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-06/LOPES_DIEGO_L_06-22-2024.png",
        fightHistory: [
            { result: "Победа",  record: "26-6",  opponent: "Шан Вэйли",              oppFlag: "🇨🇳", method: "Сдача (удушение)",    event: "UFC 308",          date: "26 окт 2024", round: 1, time: "3:15",  location: "Абу-Даби, ОАЭ",  note: "Выступление вечера" },
            { result: "Победа",  record: "25-6",  opponent: "Брайан Ортега",           oppFlag: "🇺🇸", method: "TKO (удары)",          event: "UFC 303",          date: "29 июн 2024", round: 3, time: "1:11",  location: "Лас-Вегас, США", note: "Выступление вечера" },
        ]
    },
    {
        id: "movsar_evloev",
        name: "Movsar Evloev",
        nickname: "—",
        division: "Featherweight",
        rank: 4,
        record: "18-0-0",
        sherdog: { ko: 3, sub: 4, dec: 11, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.30, strAcc: 49, sapm: 2.70, strDef: 63, tdAvg: 4.71, tdAcc: 51, tdDef: 71 },
        verdictRating: 930,
        nationality: "Russia", flag: "🇷🇺",
        height: "5'7\" (170 cm)", reach: "72.0\" (183 cm)", stance: "Orthodox", age: 32,
        stats: { striking: 82, wrestling: 98, grappling: 93, cardio: 97, power: 74, defense: 95 },
        bio: "Undefeated Greco-Roman wrestling prodigy with high-altitude endurance.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-04/EVLOEV_MOVSAR_L.png",
        fightHistory: [
            { result: "Победа",  record: "18-0",  opponent: "Брайан Ортега",           oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC Fight Night",  date: "23 ноя 2024", round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "17-0",  opponent: "Арнольд Аллен",           oppFlag: "🇬🇧", method: "Единогласное решение",event: "UFC Fight Night",  date: "18 мар 2023", round: 3, time: "5:00",  location: "Лондон, Великобритания", note: "" },
        ]
    },

    // =========================================================================
    // BANTAMWEIGHT (ЛЕГЧАЙШИЙ ВЕС)
    // =========================================================================
    {
        id: "merab_dvalishvili",
        name: "Merab Dvalishvili",
        nickname: "The Machine",
        division: "Bantamweight",
        rank: "C",
        record: "18-4-0",
        sherdog: { ko: 3, sub: 1, dec: 14, lossesKo: 0, lossesSub: 1, lossesDec: 3 },
        ufcStats: { slpm: 4.50, strAcc: 41, sapm: 2.37, strDef: 57, tdAvg: 6.43, tdAcc: 36, tdDef: 81 },
        verdictRating: 970,
        nationality: "Georgia", flag: "🇬🇪",
        height: "5'6\" (168 cm)", reach: "68.0\" (173 cm)", stance: "Orthodox", age: 35,
        stats: { striking: 84, wrestling: 99, grappling: 92, cardio: 100, power: 76, defense: 91 },
        bio: "UFC Bantamweight Champion with unmatched pace and UFC record takedown attempts per fight.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-09/DVALISHVILI_MERAB_L_BELT_09-14-2024.png",
        fightHistory: [
            { result: "Победа",  record: "18-4",  opponent: "Шон О'Мэлли",            oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC 306",          date: "14 сен 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Завоевал титул; Бой вечера" },
            { result: "Победа",  record: "17-4",  opponent: "Петр Ян",                  oppFlag: "🇷🇺", method: "Единогласное решение",event: "UFC 296",          date: "16 дек 2023", round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа",  record: "16-4",  opponent: "Хосе Альдо",               oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 278",          date: "20 авг 2022", round: 3, time: "5:00",  location: "Солт-Лейк-Сити, США", note: "" },
        ]
    },
    {
        id: "umar_nurmagomedov",
        name: "Umar Nurmagomedov",
        nickname: "—",
        division: "Bantamweight",
        rank: 1,
        record: "18-0-0",
        sherdog: { ko: 2, sub: 7, dec: 9, lossesKo: 0, lossesSub: 0, lossesDec: 0 },
        ufcStats: { slpm: 4.75, strAcc: 50, sapm: 0.56, strDef: 69, tdAvg: 4.50, tdAcc: 57, tdDef: 100 },
        verdictRating: 960,
        nationality: "Russia", flag: "🇷🇺",
        height: "5'8\" (173 cm)", reach: "69.0\" (175 cm)", stance: "Orthodox", age: 30,
        stats: { striking: 90, wrestling: 97, grappling: 95, cardio: 95, power: 80, defense: 94 },
        bio: "Undefeated bantamweight contender. Dynamic Taekwondo and Dagestani grappling.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-02/NURMAGOMEDOV_UMAR_L_02-17-2024.png",
        fightHistory: [
            { result: "Победа",  record: "18-0",  opponent: "Кори Сандхаген",          oppFlag: "🇺🇸", method: "Единогласное решение",event: "UFC Fight Night",  date: "16 ноя 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Выступление вечера" },
            { result: "Победа",  record: "17-0",  opponent: "Мераб Двалишвили",        oppFlag: "🇬🇪", method: "Единогласное решение",event: "UFC 311",          date: "18 янв 2025", round: 5, time: "5:00",  location: "Инглвуд, США",   note: "Завоевал временный чемпионский пояс" },
        ]
    },
    {
        id: "petr_yan",
        name: "Petr Yan",
        nickname: "No Mercy",
        division: "Bantamweight",
        rank: 2,
        record: "17-5-0",
        sherdog: { ko: 7, sub: 1, dec: 9, lossesKo: 0, lossesSub: 0, lossesDec: 5 },
        ufcStats: { slpm: 5.03, strAcc: 53, sapm: 4.00, strDef: 62, tdAvg: 1.71, tdAcc: 52, tdDef: 85 },
        verdictRating: 940,
        nationality: "Russia", flag: "🇷🇺",
        height: "5'7\" (170 cm)", reach: "67.0\" (170 cm)", stance: "Switch", age: 33,
        stats: { striking: 97, wrestling: 88, grappling: 82, cardio: 94, power: 88, defense: 93 },
        bio: "Former Bantamweight Champion & Master of Sport in Boxing.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-10/YAN_PETR_L.png",
        fightHistory: [
            { result: "Поражение",record: "17-5", opponent: "Умар Нурмагомедов",      oppFlag: "🇷🇺", method: "Единогласное решение",event: "UFC Fight Night",  date: "16 ноя 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "17-4", opponent: "Мераб Двалишвили",       oppFlag: "🇬🇪", method: "Единогласное решение",event: "UFC 296",          date: "16 дек 2023", round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "17-3",  opponent: "Сон Яне",                 oppFlag: "🇨🇳", method: "Единогласное решение",event: "UFC Fight Night",  date: "20 май 2023",  round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "" },
        ]
    },
    {
        id: "sean_omalley",
        name: "Sean O'Malley",
        nickname: "Suga",
        division: "Bantamweight",
        rank: 3,
        record: "18-2-0 (1 NC)",
        sherdog: { ko: 12, sub: 1, dec: 5, lossesKo: 1, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 7.25, strAcc: 61, sapm: 3.52, strDef: 62, tdAvg: 0.45, tdAcc: 42, tdDef: 60 },
        verdictRating: 935,
        nationality: "USA", flag: "🇺🇸",
        height: "5'11\" (180 cm)", reach: "72.0\" (183 cm)", stance: "Switch", age: 31,
        stats: { striking: 97, wrestling: 65, grappling: 68, cardio: 89, power: 88, defense: 88 },
        bio: "Former Bantamweight Champion with sniper precision striking and superstar charisma.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-08/OMALLEY_SEAN_L_BELT.png",
        fightHistory: [
            { result: "Поражение",record: "18-2", opponent: "Мераб Двалишвили",       oppFlag: "🇬🇪", method: "Единогласное решение",event: "UFC 306",          date: "14 сен 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Потерял титул" },
            { result: "Победа",  record: "18-1",  opponent: "Марлон Вера",             oppFlag: "🇪🇨", method: "Единогласное решение",event: "UFC 299",          date: "9 мар 2024",  round: 5, time: "5:00",  location: "Майами, США",     note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "17-1",  opponent: "Альжамейн Стерлинг",      oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC 292",          date: "19 авг 2023", round: 2, time: "2:30",  location: "Бостон, США",     note: "Завоевал титул; Нокаут вечера" },
        ]
    },
    {
        id: "cory_sandhagen",
        name: "Cory Sandhagen",
        nickname: "The Sandman",
        division: "Bantamweight",
        rank: 4,
        record: "17-5-0",
        sherdog: { ko: 7, sub: 3, dec: 7, lossesKo: 0, lossesSub: 1, lossesDec: 4 },
        ufcStats: { slpm: 5.33, strAcc: 44, sapm: 3.40, strDef: 57, tdAvg: 1.36, tdAcc: 33, tdDef: 64 },
        verdictRating: 915,
        nationality: "USA", flag: "🇺🇸",
        height: "5'11\" (180 cm)", reach: "70.0\" (178 cm)", stance: "Switch", age: 34,
        stats: { striking: 94, wrestling: 85, grappling: 84, cardio: 95, power: 84, defense: 88 },
        bio: "Creative switch-stance striker famous for flying knees and adaptable game.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-10/SANDHAGEN_CORY_L_10-21.png",
        fightHistory: [
            { result: "Поражение",record: "17-5", opponent: "Умар Нурмагомедов",      oppFlag: "🇷🇺", method: "Единогласное решение",event: "UFC Fight Night",  date: "16 ноя 2024", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "17-4",  opponent: "Сон Яне",                 oppFlag: "🇨🇳", method: "Единогласное решение",event: "UFC Fight Night",  date: "2 сен 2023",  round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "" },
        ]
    },

    // =========================================================================
    // FLYWEIGHT (НАИЛЕГЧАЙШИЙ ВЕС)
    // =========================================================================
    {
        id: "alexandre_pantoja",
        name: "Alexandre Pantoja",
        nickname: "The Cannibal",
        division: "Flyweight",
        rank: "C",
        record: "28-5-0",
        sherdog: { ko: 8, sub: 10, dec: 10, lossesKo: 0, lossesSub: 0, lossesDec: 5 },
        ufcStats: { slpm: 4.32, strAcc: 48, sapm: 3.80, strDef: 52, tdAvg: 2.20, tdAcc: 40, tdDef: 67 },
        verdictRating: 950,
        nationality: "Brazil", flag: "🇧🇷",
        height: "5'5\" (165 cm)", reach: "68.0\" (173 cm)", stance: "Orthodox", age: 36,
        stats: { striking: 84, wrestling: 87, grappling: 96, cardio: 94, power: 80, defense: 86 },
        bio: "UFC Flyweight Champion. Ferocious scrambling grappler with iron chin and non-stop submissions.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-07/PANTOJA_ALEXANDRE_L_BELT_07-27-2024.png",
        fightHistory: [
            { result: "Победа",  record: "28-5",  opponent: "Стив Эрцег",              oppFlag: "🇦🇺", method: "Единогласное решение",event: "UFC 307",          date: "5 окт 2024",  round: 5, time: "5:00",  location: "Солт-Лейк-Сити, США", note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "27-5",  opponent: "Брэндон Морено III",      oppFlag: "🇲🇽", method: "KO (удары)",           event: "UFC 290",          date: "8 июл 2023",  round: 3, time: "4:26",  location: "Лас-Вегас, США", note: "Завоевал титул; Нокаут вечера" },
        ]
    },
    {
        id: "brandon_moreno",
        name: "Brandon Moreno",
        nickname: "The Assassin Baby",
        division: "Flyweight",
        rank: 1,
        record: "21-8-2",
        sherdog: { ko: 5, sub: 11, dec: 5, lossesKo: 0, lossesSub: 0, lossesDec: 8 },
        ufcStats: { slpm: 3.80, strAcc: 42, sapm: 3.40, strDef: 56, tdAvg: 1.73, tdAcc: 44, tdDef: 64 },
        verdictRating: 925,
        nationality: "Mexico", flag: "🇲🇽",
        height: "5'7\" (170 cm)", reach: "70.0\" (178 cm)", stance: "Orthodox", age: 32,
        stats: { striking: 91, wrestling: 82, grappling: 90, cardio: 94, power: 78, defense: 88 },
        bio: "Two-time Flyweight Champion. First Mexican-born UFC champion with sharp boxing.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-01/MORENO_BRANDON_L_BELT.png",
        fightHistory: [
            { result: "Поражение",record: "21-8", opponent: "Александр Пантоха",      oppFlag: "🇧🇷", method: "KO (удары)",           event: "UFC 290",          date: "8 июл 2023",  round: 3, time: "4:26",  location: "Лас-Вегас, США", note: "" },
            { result: "Победа",  record: "21-7",  opponent: "Амир Альбази",            oppFlag: "🇨🇦", method: "Сдача (удушение)",    event: "UFC 288",          date: "6 май 2023",   round: 4, time: "3:39",  location: "Ньюарк, США",    note: "Завоевал временный титул" },
        ]
    },
    {
        id: "kai_kara_france",
        name: "Kai Kara-France",
        nickname: "Don't Blink",
        division: "Flyweight",
        rank: 3,
        record: "25-11-0 (1 NC)",
        sherdog: { ko: 12, sub: 3, dec: 10, lossesKo: 3, lossesSub: 3, lossesDec: 5 },
        ufcStats: { slpm: 4.57, strAcc: 40, sapm: 3.57, strDef: 65, tdAvg: 0.43, tdAcc: 25, tdDef: 88 },
        verdictRating: 890,
        nationality: "New Zealand", flag: "🇳🇿",
        height: "5'4\" (163 cm)", reach: "69.0\" (175 cm)", stance: "Orthodox", age: 33,
        stats: { striking: 92, wrestling: 78, grappling: 72, cardio: 90, power: 89, defense: 85 },
        bio: "City Kickboxing power puncher with explosive overhand KO power.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2022-07/KARA-FRANCE_KAI_L.png",
        fightHistory: [
            { result: "Победа",  record: "25-11", opponent: "Дэвид Дворак",           oppFlag: "🇨🇿", method: "KO (удары)",           event: "UFC Fight Night",  date: "2 ноя 2024",  round: 1, time: "1:22",  location: "Лас-Вегас, США", note: "Нокаут вечера" },
            { result: "Поражение",record: "24-11",opponent: "Амир Альбази",            oppFlag: "🇨🇦", method: "Единогласное решение",event: "UFC Fight Night",  date: "27 апр 2024", round: 3, time: "5:00",  location: "Канада",          note: "" },
        ]
    },
    {
        id: "tatsuro_taira",
        name: "Tatsuro Taira",
        nickname: "—",
        division: "Flyweight",
        rank: 4,
        record: "16-1-0",
        sherdog: { ko: 5, sub: 7, dec: 4, lossesKo: 0, lossesSub: 0, lossesDec: 1 },
        ufcStats: { slpm: 3.56, strAcc: 54, sapm: 2.10, strDef: 50, tdAvg: 2.12, tdAcc: 45, tdDef: 70 },
        verdictRating: 905,
        nationality: "Japan", flag: "🇯🇵",
        height: "5'7\" (170 cm)", reach: "70.0\" (178 cm)", stance: "Orthodox", age: 26,
        stats: { striking: 83, wrestling: 90, grappling: 94, cardio: 91, power: 76, defense: 87 },
        bio: "Japanese grappling prodigy with body triangle back-mount control.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2024-02/TAIRA_TATSURO_L.png",
        fightHistory: [
            { result: "Победа",  record: "16-1",  opponent: "Давид Дворак",           oppFlag: "🇨🇿", method: "Единогласное решение",event: "UFC Fight Night",  date: "23 ноя 2024", round: 3, time: "5:00",  location: "Лас-Вегас, США", note: "" },
            { result: "Поражение",record: "15-1", opponent: "Брэндон Ройвал",         oppFlag: "🇺🇸", method: "Раздельное решение",  event: "UFC 302",          date: "1 июн 2024",  round: 3, time: "5:00",  location: "Ньюарк, США",    note: "" },
        ]
    },

    // =========================================================================
    // WOMEN'S STRAWWEIGHT
    // =========================================================================
    {
        id: "zhang_weili",
        name: "Zhang Weili",
        nickname: "Magnum",
        division: "Strawweight",
        rank: "C",
        record: "25-3-0",
        sherdog: { ko: 11, sub: 8, dec: 6, lossesKo: 1, lossesSub: 0, lossesDec: 2 },
        ufcStats: { slpm: 5.94, strAcc: 51, sapm: 3.44, strDef: 53, tdAvg: 2.29, tdAcc: 42, tdDef: 66 },
        verdictRating: 965,
        nationality: "China", flag: "🇨🇳",
        height: "5'4\" (163 cm)", reach: "63.0\" (160 cm)", stance: "Switch", age: 36,
        stats: { striking: 95, wrestling: 92, grappling: 90, cardio: 96, power: 93, defense: 90 },
        bio: "Two-time UFC Women's Strawweight Champion. Explosive Sanda kickboxer with heavy power.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-07/ZHANG_WEILI_L_BELT.png",
        fightHistory: [
            { result: "Победа",  record: "25-3",  opponent: "Ян Сяонань",             oppFlag: "🇨🇳", method: "TKO (удары)",          event: "UFC 300",          date: "13 апр 2024", round: 3, time: "4:28",  location: "Лас-Вегас, США", note: "Защита титула; Бой вечера" },
            { result: "Победа",  record: "24-3",  opponent: "Аманда Леймо",            oppFlag: "🇺🇸", method: "KO (удары)",           event: "UFC 292",          date: "19 авг 2023", round: 2, time: "4:30",  location: "Бостон, США",     note: "Защита титула; Нокаут вечера" },
            { result: "Победа",  record: "23-3",  opponent: "Карла Эспарса",           oppFlag: "🇺🇸", method: "Сдача (удушение)",    event: "UFC 274",          date: "7 май 2022",   round: 3, time: "2:32",  location: "Финикс, США",    note: "Завоевала вакантный титул; Выступление вечера" },
        ]
    },
    {
        id: "valentina_shevchenko",
        name: "Valentina Shevchenko",
        nickname: "Bullet",
        division: "Women's Flyweight",
        rank: "C",
        record: "24-4-1",
        sherdog: { ko: 8, sub: 7, dec: 9, lossesKo: 1, lossesSub: 1, lossesDec: 2 },
        ufcStats: { slpm: 3.29, strAcc: 52, sapm: 1.86, strDef: 63, tdAvg: 2.56, tdAcc: 63, tdDef: 71 },
        verdictRating: 975,
        nationality: "Kyrgyzstan / Peru", flag: "🇰🇬",
        height: "5'5\" (165 cm)", reach: "67.0\" (170 cm)", stance: "Southpaw", age: 38,
        stats: { striking: 97, wrestling: 91, grappling: 89, cardio: 97, power: 86, defense: 96 },
        bio: "UFC Women's Flyweight Champion & 17-time World Muay Thai Champion.",
        image: "https://dmxg5wxfqgde4.cloudfront.net/styles/athlete_bio_full_body/s3/2023-06/SHEVCHENKO_VALENTINA_L_BELT.png",
        fightHistory: [
            { result: "Победа",  record: "24-4",  opponent: "Тайла Сантос",            oppFlag: "🇧🇷", method: "Единогласное решение",event: "UFC 304",          date: "27 июл 2024", round: 5, time: "5:00",  location: "Манчестер, Великобритания", note: "Защита титула" },
            { result: "Победа",  record: "23-4",  opponent: "Хамзат Маулоу",           oppFlag: "🇫🇷", method: "Единогласное решение",event: "UFC Fight Night",  date: "25 ноя 2023", round: 5, time: "5:00",  location: "Лас-Вегас, США", note: "Защита титула" },
        ]
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = fighters;
}
